<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'AdvanceDeclineDifference';
$helperName = 'ADDIFF';
$helperArguments = '["SPY", "QQQ"]';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '"QQQ"]';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'advance-decline-difference';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>