<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "AdvanceDeclineDifference";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/advance-decline-difference.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>