<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "DoubleExponentialMovingAverage";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/double-exponential-moving-average.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>