<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = true;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'Correlation';
$helperName = 'C';
$pyHelperName = 'c';
$helperArguments = 'symbol, reference, 20, correlationType=CorrelationType.Pearson';
$properties = array();
$pyProperties = array();
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '"", symbol, reference, 20, correlationType=CorrelationType.Pearson';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'correlation';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>