<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'Correlation';
$helperName = 'C';
$pyHelperName = 'c';
$helperArguments = 'symbol, reference, 20, correlationType=CorrelationType.Pearson';
$hasReference = true;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>