<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'AdvanceDeclineRatio';
$helperName = 'ADR';
$helperArguments = '[self.symbol, Symbol.Create';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'Symbol.Create';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'advance-decline-ratio';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>