<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'MidPrice';
$helperName = 'MIDPRICE';
$helperArguments = '"SPY", 20';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mid-price';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>