<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'UltimateOscillator';
$helperName = 'ULTOSC';
$pyHelperName = 'ultosc';
$helperArguments = 'symbol, 5, 10, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>