<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'DeMarkerIndicator';
$helperName = 'DEM';
$helperArguments = '"SPY", 20, MovingAverageType.Simple';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20, MovingAverageType.Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'de-marker-indicator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>