<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "SchaffTrendCycle";
$indicatorVariable = "stc";
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>