<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'McClellanSummationIndex';
$helperName = 'McClellanSummationIndex';
$pyHelperName = 'mc_clellan_summation_index';
$helperArguments = 'symbol';
$properties = array("McClellanOscillator");
$pyProperties = array("mc_clellan_oscillator");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mc-clellan-summation-index';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>