<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'ExponentialMovingAverage';
$helperName = 'EMA';
$helperArguments = '"SPY", 20, 0.5';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '20, 0.5';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'exponential-moving-average';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>