<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AverageDirectionalMovementIndexRating';
$helperName = 'AverageDirectionalMovementIndexRating';
$pyHelperName = 'average_directional_movement_index_rating';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("ADX");
$pythonProperties = array("adx");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>