<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AverageDirectionalMovementIndexRating';
$helperName = 'ADXR';
$pyHelperName = 'adxr';
$helperArguments = 'symbol, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("ADX");
$pythonProperties = array("adx");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>