<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "AverageDirectionalMovementIndexRating";
$indicatorVariable = "adxr";
$csharpProperties = array("ADX");
$pythonProperties = array("adx");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>