<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "RelativeStrengthIndex";
$indicatorVariable = "rsi";
$csharpProperties = array("AverageLoss","AverageGain");
$pythonProperties = array("average_loss","average_gain");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>