<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'AwesomeOscillator';
$helperName = 'AO';
$helperArguments = '"SPY", 10, 20, Simple';
$properties = array("SlowAo","FastAo");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '10, 20, Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'awesome-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>