<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "TimeProfile";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/time-profile.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>