<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'ChaikinMoneyFlow';
$helperName = 'CMF';
$helperArguments = 'symbol, 20';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '"SPY", 20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'chaikin-money-flow';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>