<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ParabolicStopAndReverseExtended';
$helperName = 'ParabolicStopAndReverseExtended';
$pyHelperName = 'parabolic_stop_and_reverse_extended';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>