<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'HeikinAshi';
$helperName = 'HeikinAshi';
$pyHelperName = 'heikin_ashi';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Open","High","Low","Close","Volume");
$pythonProperties = array("open","high","low","close","volume");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>