<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'Delta';
$helperName = 'D';
$pyHelperName = 'd';
$helperArguments = 'option_symbol, option_mirror_symbol';
$hasReference = false;
$isOptionIndicator = true;
$csharpProperties = array("ImpliedVolatility","OptionSymbol","RiskFreeRate","DividendYield","Price","OppositePrice","UnderlyingPrice");
$pythonProperties = array("implied_volatility","option_symbol","risk_free_rate","dividend_yield","price","opposite_price","underlying_price");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>