<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'KeltnerChannels';
$helperName = 'KCH';
$helperArguments = 'symbol, 20, 2, MovingAverageType.Simple';
$properties = array("MiddleBand","UpperBand","LowerBand","AverageTrueRange");
$pyProperties = array("middle_band","upper_band","lower_band","average_True_range");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '20, 2, MovingAverageType.Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'keltner-channels';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>