<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "KeltnerChannels";
$indicatorVariable = "kch";
$csharpProperties = array("MiddleBand","UpperBand","LowerBand","AverageTrueRange");
$pythonProperties = array("middle_band","upper_band","lower_band","average_True_range");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>