<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "McClellanSummationIndex";
$indicatorVariable = "msi";
$csharpProperties = array("McClellanOscillator");
$pythonProperties = array("mc_clellan_oscillator");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>