<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'KeltnerChannels';
$helperName = 'KCH';
$helperArguments = '"SPY", 20, 2, MovingAverageType.Simple';
$properties = array("MiddleBand","UpperBand","LowerBand","AverageTrueRange");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20, 2, MovingAverageType.Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'keltner-channels';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>