<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'Vortex';
$helperName = 'VTX';
$pyHelperName = 'vtx';
$helperArguments = 'symbol, 14';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("PlusVortex","MinusVortex");
$pythonProperties = array("plus_vortex","minus_vortex");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>