<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'FilteredIdentity';
$helperName = 'FilteredIdentity';
$pyHelperName = 'filtered_identity';
$helperArguments = 'symbol, filter = lambda x: x.Close > x.Open';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>