<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'KaufmanAdaptiveMovingAverage';
$helperName = 'KAMA';
$pyHelperName = 'kama';
$helperArguments = 'symbol, 20, 10, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>