<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'BalanceOfPower';
$helperName = 'BOP';
$helperArguments = '"SPY"';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '"SPY"';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'balance-of-power';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>