<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "BalanceOfPower";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/balance-of-power.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>