<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "BalanceOfPower";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/balance-of-power.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>