<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'TasukiGap';
$helperName = 'TasukiGap';
$helperArguments = 'SPY';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'SPY';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'tasuki-gap';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>