<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = 'CandlestickPatterns.';
$typeName = 'GapSideBySideWhite';
$helperName = 'GapSideBySideWhite';
$pyHelperName = 'gap_side_by_side_white';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>