<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'RegressionChannel';
$helperName = 'RC';
$pyHelperName = 'rc';
$helperArguments = 'symbol, 20, 2';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("LinearRegression","UpperChannel","LowerChannel","Intercept","Slope");
$pythonProperties = array("linear_regression","upper_channel","lower_channel","intercept","slope");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>