<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "UltimateOscillator";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/ultimate-oscillator.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>