<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = 'CandlestickPatterns.';
$typeName = 'HighWaveCandle';
$helperName = 'HighWaveCandle';
$pyHelperName = 'high_wave_candle';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>