<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "AroonOscillator";
$indicatorVariable = "aroon";
$csharpProperties = array("AroonUp","AroonDown");
$pythonProperties = array("aroon_up","aroon_down");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>