<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AroonOscillator';
$helperName = 'AROON';
$pyHelperName = 'aroon';
$helperArguments = 'symbol, 10, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("AroonUp","AroonDown");
$pythonProperties = array("aroon_up","aroon_down");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>