<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'SqueezeMomentum';
$helperName = 'SqueezeMomentum';
$pyHelperName = 'squeeze_momentum';
$helperArguments = 'symbol';
$properties = array("BollingerBands","KeltnerChannels");
$pyProperties = array("bollinger_bands","keltner_channels");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'squeeze-momentum';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>