<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "ArnaudLegouxMovingAverage";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/arnaud-legoux-moving-average.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>