<h4 id="Indicators">Indicators</h4>
<? include(DOCS_RESOURCES."/qcalgorithm-api/a.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/abands.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ad.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/addiff.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/adosc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/adr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/advr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/adx.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/adxr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/alma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ao.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/apo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/aps.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/arima.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/aroon.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/asi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/atr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/b.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/bb.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/bop.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/c.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/cc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/cci.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/cmf.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/cmo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/create-indicator-name.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/d.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dch.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dem.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dema.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/do.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dpo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ema.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/emv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/filtered-identity.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/fish.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/frama.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/g.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/heikin-ashi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/hma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ht.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ichimoku.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/identity.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/iv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/kama.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/kch.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ker.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/logr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/lsma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/lwma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/macd.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/mad.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/mass.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/max.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/mfi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/midpoint.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/midprice.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/min.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/mom.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/momersion.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/momp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/mosc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/msi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/natr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/obv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/pphl.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ppo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/psar.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/r.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rdv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/register-indicator.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/roc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rocp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rocr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rsi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rvi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/si.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/sma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/sortino.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/sr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/stc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/std.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/sto.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/str.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/sum.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/swiss.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/t.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/t-3.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tdd.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tema.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/trima.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/trin.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/trix.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tsf.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tsi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ultosc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/v.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/vidya.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/vp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/vwap.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/warm-up-indicator.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/wilr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/wwma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/γ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/δ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/θ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ρ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/candlestick-patterns.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/enable-automatic-indicator-warm-up.html"); ?>
<style>
.code-source        { color: grey; float: right }
.object-type        { font-style: italic; }
.arg-name           { font-weight: bold; }
.subsection-header  { font-weight: bold; background-color: lightgray; }
.subsection-content { margin-left: 10px; }
</style>
