<h4 id="Indicators">Indicators</h4>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-a.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-abands.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ad.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-addiff.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-adosc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-adr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-advr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-adx.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-adxr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-alma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ao.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-apo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-aps.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-arima.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-aroon.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-asi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-atr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-b.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-bb.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-bop.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-c.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-cc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-cci.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-cmf.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-cmo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-create-indicator-name.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-d.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-dch.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-dem.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-dema.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-do.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-dpo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ema.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-emv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-filtered-identity.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-fish.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-frama.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-g.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-heikin-ashi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-hma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ht.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ichimoku.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-identity.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-iv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-kama.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-kch.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ker.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-logr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-lsma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-lwma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-macd.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-mad.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-mass.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-max.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-mfi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-midpoint.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-midprice.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-min.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-mom.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-momersion.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-momp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-mosc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-msi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-natr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-obv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-pphl.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ppo.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-psar.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-r.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rdv.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-register-indicator.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-roc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rocp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rocr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rsi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-rvi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-si.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-sma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-sortino.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-sr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-stc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-std.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-sto.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-str.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-sum.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-swiss.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-t.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-t-3.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-tdd.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-tema.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-tp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-tr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-trima.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-trin.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-trix.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-tsf.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-tsi.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ultosc.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-v.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-vidya.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-vp.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-vwap.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-warm-up-indicator.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-wilr.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-wwma.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-γ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-δ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-θ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-ρ.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-candlestick-patterns.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-enable-automatic-indicator-warm-up.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/qcalgorithm-t3.html"); ?>
<style>
.code-source        { color: grey; float: right }
.object-type        { font-style: italic; }
.arg-name           { font-weight: bold; }
.subsection-header  { font-weight: bold; background-color: lightgray; }
.subsection-content { margin-left: 10px; }
</style>
