<? include(DOCS_RESOURCES."/qcalgorithm-api/abandoned-baby.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/account-type.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/advance-block.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/algorithm-mode.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/algorithm-status.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/belt-hold.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/breakaway.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/brokerage-message-event.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/brokerage-name.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/cfd.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/chart.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/closing-marubozu.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/concealed-baby-swallow.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/correlation-type.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/counterattack.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/crypto.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/crypto-future.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dark-cloud-cover.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/delistings.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/deployment-target.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/derivative-oscillator.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dividends.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/doji.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/doji-star.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/dragonfly-doji.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/engulfing.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/equity.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/evening-doji-star.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/evening-star.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/forex.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/fundamental.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/future.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/gap-side-by-side-white.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/gravestone-doji.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/hammer.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/hanging-man.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/harami.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/harami-cross.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/high-wave-candle.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/hikkake.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/hikkake-modified.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/history-request.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/homing-pigeon.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/identical-three-crows.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/in-neck.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/index.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/insight.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/inverted-hammer.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/kicking.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/kicking-by-length.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/ladder-bottom.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/long-legged-doji.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/long-line-candle.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/marubozu.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/mat-hold.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/matching-low.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/morning-doji-star.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/morning-star.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/moving-average-type.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/on-neck.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/option.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/option-pricing-model-type.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/option-strategy.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/order-event.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/order-ticket.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/piercing.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/resolution.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rickshaw-man.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/rise-fall-three-methods.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/scheduled-event.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/security.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/security-changes.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/security-exchange-hours.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/security-type.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/separating-lines.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/series-type.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/shooting-star.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/short-line-candle.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/slice.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/spinning-top.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/splits.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/stalled-pattern.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/stick-sandwich.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/submit-order-request.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/swiss-army-knife-tool.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/symbol.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/symbol-changed-events.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/symbol-properties.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/takuri.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tasuki-gap.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/three-black-crows.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/three-inside.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/three-line-strike.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/three-outside.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/three-stars-in-south.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/three-white-soldiers.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/thrusting.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/trade-bar.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/tristar.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/two-crows.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/unique-three-river.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/universe.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/universe-settings.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/up-down-gap-three-methods.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/upside-gap-two-crows.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/float-exponential-moving-average.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/int-legged-doji.html"); ?>
<? include(DOCS_RESOURCES."/qcalgorithm-api/int-line-candle.html"); ?>

<style>
.code-source        { color: grey; float: right }
.object-type        { font-style: italic; }
.arg-name           { font-weight: bold; }
.subsection-header  { font-weight: bold; background-color: lightgray; }
.subsection-content { margin-left: 10px; }
</style>
