<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = false;
$helperPrefix = '';
$typeName = 'Delay';
$helperName = 'Delay';
$helperArguments = 'symbol';
$properties = array();
$otherProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'delay';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>