<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'Gamma';
$helperName = 'Gamma';
$pyHelperName = 'gamma';
$helperArguments = 'symbol';
$properties = array("ImpliedVolatility","OptionSymbol","RiskFreeRate","DividendYield","Price","OppositePrice","UnderlyingPrice");
$pyProperties = array("implied_volatility","option_symbol","risk_free_rate","dividend_yield","price","opposite_price","underlying_price");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'gamma';
$isOptionIndicator = true;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>