<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'TrueStrengthIndex';
$helperName = 'TrueStrengthIndex';
$pyHelperName = 'true_strength_index';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Signal");
$pythonProperties = array("signal");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>