<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'TrueStrengthIndex';
$helperName = 'TSI';
$pyHelperName = 'tsi';
$helperArguments = 'symbol, 25, 13, 7, MovingAverageType.Exponential';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Signal");
$pythonProperties = array("signal");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>