<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'LeastSquaresMovingAverage';
$helperName = 'LeastSquaresMovingAverage';
$pyHelperName = 'least_squares_moving_average';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Intercept","Slope");
$pythonProperties = array("intercept","slope");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>