<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'RelativeStrengthIndex';
$helperName = 'RSI';
$pyHelperName = 'rsi';
$helperArguments = 'symbol, 14';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("AverageLoss","AverageGain");
$pythonProperties = array("average_loss","average_gain");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>