<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'McClellanSummationIndex';
$helperName = 'MSI';
$pyHelperName = 'msi';
$helperArguments = '[symbol, reference]';
$hasReference = true;
$isOptionIndicator = false;
$csharpProperties = array("McClellanOscillator");
$pythonProperties = array("mc_clellan_oscillator");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>