<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "McClellanOscillator";
$indicatorVariable = "mosc";
$csharpProperties = array("EMAFast","EMASlow","ADDifference");
$pythonProperties = array("ema_fast","ema_slow","ad_difference");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>