<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "TimeSeriesForecast";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/time-series-forecast.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>