<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "IchimokuKinkoHyo";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/ichimoku-kinko-hyo.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>