<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "KeltnerChannels";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/keltner-channels.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>