<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'DonchianChannel';
$helperName = 'DCH';
$helperArguments = '"SPY", 20, 20';
$properties = array("UpperBand","LowerBand");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20, 20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'donchian-channel';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>