<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "WilderSwingIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/-wilder-swing-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>