<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'CoppockCurve';
$helperName = 'CC';
$helperArguments = '"SPY", 11, 14, 10';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '11, 14, 10';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'coppock-curve';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>