<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "InternalBarStrength";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/internal-bar-strength.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>