<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'Beta';
$helperName = 'B';
$helperArguments = 'Symbol.Create';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'Symbol.Create';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'beta';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>