<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = true;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'AdvanceDeclineDifference';
$helperName = 'ADDIFF';
$helperArguments = '[symbol, reference]';
$properties = array();
$pyProperties = array();
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '""';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'advance-decline-difference';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>