<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "ChandeMomentumOscillator";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/chande-momentum-oscillator.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>