<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'McClellanSummationIndex';
$helperName = 'MSI';
$helperArguments = '';
$properties = array("McClellanOscillator");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '""';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mc-clellan-summation-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>