<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'RegressionChannel';
$helperName = 'RegressionChannel';
$pyHelperName = 'regression_channel';
$helperArguments = 'symbol';
$properties = array("LinearRegression","UpperChannel","LowerChannel","Intercept","Slope");
$pyProperties = array("linear_regression","upper_channel","lower_channel","intercept","slope");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'regression-channel';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>