<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "VolumeWeightedAveragePriceIndicator";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/-volume-weighted-average-price-indicator.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>