<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "RelativeMovingAverage";
$indicatorVariable = "rma";
$csharpProperties = array("ShortAverage","MediumAverage","LongAverage");
$pythonProperties = array("short_average","medium_average","long_average");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>