<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'McClellanOscillator';
$helperName = 'MOSC';
$helperArguments = '[symbol, Symbol.Create("QQQ", SecurityType.Equity, Market.USA)]';
$properties = array("EMAFast","EMASlow","ADDifference");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '""';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mc-clellan-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>