<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'FilteredIdentity';
$helperName = 'FilteredIdentity';
$helperArguments = '"SPY", filter = lambda x: x.Close > x.Open';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = 'filter = lambda x: x.Close > x.Open';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'filtered-identity';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>