<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hadReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'VolumeProfile';
$helperName = 'VP';
$helperArguments = 'symbol, 3, 0.70, 0.05';
$properties = array();
$otherProperties = array("ProfileHigh","ProfileLow","POCPrice","POCVolume","ValueAreaVolume","ValueAreaHigh","ValueAreaLow");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '"", 3, 0.70, 0.05';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'volume-profile';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>