"""Generate the price tables of the LEAN CLI dataset Price pages and the Object Store
storage table from the same sources as the pricing skill.

Writes HTML fragments that the pages include:

    Resources/datasets/lean-cli-prices/<page>-<table>.html
    Resources/datasets/us-equity-security-master-price.html
    Resources/datasets/us-futures-security-master-price.html
    Resources/object-store/storage-sizes.html

Sources:
    the Pricing page catalog (qc_plan_prices.catalog)  -> per-tier bulk and storage prices
    /market/sections/read (qc_dataset_prices)          -> dataset-page prices the catalog lacks
    /data/prices (qc_dataset_prices.file_rules)        -> QCC per file, what `lean data download` charges

The prose and worked examples of the Price pages stay hand-written.

Needs QUANTCONNECT_USER_ID and QUANTCONNECT_API_TOKEN.

Usage:
    python code-generators/docs_price_tables.py
"""

from pathlib import Path

from qc_dataset_prices import datasets, file_rules, price_rows, quote_org
from qc_plan_prices import TIER_LABELS, TIERS, catalog

ROOT = Path(__file__).resolve().parents[1]
RESOURCES = ROOT / "Resources"
HEADER = "<!-- Generated by code-generators/docs_price_tables.py. Do not edit. -->\n"

EQUITY_FILES = "One file per security per trading day per data format. Quote and trade data are separate files."
FUTURES_FILES = ("One file per ticker per trading day per data format. Trade, quote, and open "
                 "interest data are separate files.")
FUTURES_BAR_FILES = "One file per ticker per data format. Trade, quote, and open interest data are separate files."

# Each page: its tables, in page order. Row labels map to catalog names; a label that
# joins several resolutions must have equal prices on every tier, or generation fails.
PAGES = {
    "us-equity": {
        "bulk": ("US Equity {} History by AlgoSeek",
                 ["Tick", "Second", "Minute", "Hour", "Daily"]),
        # The page says the updates cost the same for every resolution.
        "flat_updates": ("US Equity {} Updates by AlgoSeek",
                         ["Tick", "Second", "Minute", "Hour", "Daily"]),
        "total": [("US Equity Security Master", "Subscription", "sm:US Equity"),
                  ("US Equities", "Minute", "US Equity Minute {} by AlgoSeek")],
        "per_file": [
            ("Tick", EQUITY_FILES, "US Equities Tick Download by AlgoSeek"),
            ("Second", EQUITY_FILES, "US Equity Second Download by AlgoSeek"),
            ("Minute", EQUITY_FILES, "US Equity Minute Download by AlgoSeek"),
            ("Hour", "One file per security.", "US Equity Hour Download by AlgoSeek"),
            ("Daily", "One file per security.", "US Equity Daily Download by AlgoSeek"),
        ],
    },
    "us-equity-options": {
        "bulk": ("US Equity Options {} History by AlgoSeek", ["Minute", "Hour", "Daily"]),
        "updates": ("US Equity Options {} Updates by AlgoSeek", ["Minute", "Hour", "Daily"]),
        "universe": "US Equity Option Universe {} by QuantConnect",
        "total": [("US Equity Security Master", "Subscription", "sm:US Equity"),
                  ("US Equity Option Universe", "Subscription",
                   "US Equity Option Universe {} by QuantConnect"),
                  ("US Equities", "Minute", "US Equity Minute {} by AlgoSeek"),
                  ("US Equity Options", "Minute", "US Equity Options Minute {} by AlgoSeek")],
        "per_file": [
            ("Minute", "One file per Option per trading day per data format. Quote, trade, and "
             "open interest data are separate files.", "AlgoSeek Options - Minute Download"),
            ("Hour", "One file per Option per year per data format. Trade and open interest "
             "data are separate files.", "AlgoSeek Options - Hour Download"),
            ("Daily", "One file per Option per year. Trade and open interest data are separate "
             "files.", "AlgoSeek Options - Daily Download"),
        ],
    },
    "forex": {
        "total": [("FOREX Data", "Subscription", "Forex - Minute {}")],
        "same_for_all": "Forex - {} {}",
        "per_file": [
            ("Second", "One file per currency pair per trading day.", "Forex - Second Download"),
            ("Minute", "One file per currency pair per trading day.", "Forex - Minute Download"),
            ("Hour", "One file per currency pair.", "Forex - Hour Download"),
            ("Daily", "One file per currency pair.", "Forex - Daily Download"),
        ],
    },
    "us-futures": {
        "bulk": ("US Futures {} History by AlgoSeek",
                 [("Tick, Second, and Minute", ["Tick", "Second", "Minute"]), "Hour", "Daily"]),
        "updates": ("US Futures {} Updates by AlgoSeek",
                    [("Tick, Second, and Minute", ["Tick", "Second", "Minute"]), "Hour", "Daily"]),
        "universe": "US Future Universe {} by QuantConnect",
        "total": [("US Futures Security Master", "Subscription", "sm:US Futures"),
                  ("US Future Universe", "Subscription", "US Future Universe {} by QuantConnect"),
                  ("US Futures", "Minute", "US Futures Minute {} by AlgoSeek")],
        "per_file": [
            ("Tick", FUTURES_FILES, "US Futures Tick Download by AlgoSeek"),
            ("Second", FUTURES_FILES, "US Futures Second Download by AlgoSeek"),
            ("Minute", FUTURES_FILES, "US Futures Minute Download by AlgoSeek"),
            ("Hour", FUTURES_BAR_FILES, "US Futures Hour Download by AlgoSeek"),
            ("Daily", FUTURES_BAR_FILES, "US Futures Daily Download by AlgoSeek"),
        ],
    },
    "us-index-options": {
        "bulk": ("US Index Options {} History by AlgoSeek", ["Minute", "Hour", "Daily"]),
        "updates": ("US Index Options {} Updates by AlgoSeek", ["Minute", "Hour", "Daily"]),
        "universe": "US Index Option Universe {} by QuantConnect",
        "total": [("US Index Option Universe", "Subscription",
                   "US Index Option Universe {} by QuantConnect"),
                  ("US Index Options", "Minute", "US Index Options Minute {} by AlgoSeek")],
        "per_file": [
            ("Minute", FUTURES_FILES, "US Index Options Minute Download by AlgoSeek"),
            ("Hour", FUTURES_BAR_FILES, "US Index Options Hour Download by AlgoSeek"),
            ("Daily", FUTURES_BAR_FILES, "US Index Options Daily Download by AlgoSeek"),
        ],
    },
    "cfd": {
        "total": [("CFD Data", "Subscription", "CFD - Minute {}")],
        "same_for_all": "CFD - {} {}",
        "per_file": [
            ("Second", "One file per contract per trading day.", "CFD - Second Download"),
            ("Minute", "One file per contract per trading day.", "CFD - Minute Download"),
            ("Hour", "One file per contract.", "CFD - Hour Download"),
            ("Daily", "One file per contract.", "CFD - Daily Download"),
        ],
    },
    "us-equity-coarse": {
        "universe": "US Equity Coarse Universe {} by QuantConnect",
        "total": [("US Equity Security Master", "Subscription", "sm:US Equity"),
                  ("US Equity Coarse Universe", "Subscription",
                   "US Equity Coarse Universe {} by QuantConnect"),
                  ("US Equities", "Minute", "US Equity Minute {} by AlgoSeek")],
    },
    "us-etf-constituents": {
        "universe": "US ETF Constituents {} by QuantConnect",
        "total": [("US Equity Security Master", "Subscription", "sm:US Equity"),
                  ("US ETF Constituents", "Subscription", "US ETF Constituents {} by QuantConnect"),
                  ("US Equities", "Minute", "US Equity Minute {} by AlgoSeek")],
    },
}

# Object Store file limits by size in GB; the catalog carries the size and price only.
STORAGE_FILES = {0.05: 1_000, 2: 20_000, 5: 50_000, 10: 100_000, 50: 500_000}


class Prices:
    def __init__(self, data: dict, rows: list[dict], rules: list[dict]):
        self.items = {it["name"]: it for key in ("dataProducts", "objectStorage")
                      for it in data.get(key) or []}
        self.page_prices = {r["sku"]: r["yearly"] for r in rows}
        self.qcc: dict[str, set] = {}
        sku_names = {r["skuId"]: r["sku"] for r in rows}
        for rule in rules:
            name = sku_names.get(rule.get("productId"))
            if name:
                self.qcc.setdefault(name, set()).add(rule.get("price") or 0)

    def yearly(self, name: str) -> list[int]:
        """Yearly price per tier. Where the catalog has none, the dataset page's price,
        which is the same on every tier (checked for the universe updates)."""
        market = (self.items.get(name) or {}).get("marketPrice") or {}
        tiers = [(market.get(t) or {}).get("yearly") for t in TIERS]
        if all(tiers):
            return tiers
        if not self.page_prices.get(name):
            raise KeyError(f"no price for {name!r} in the catalog or on its dataset page")
        return [self.page_prices[name]] * len(TIERS)

    def per_file(self, name: str) -> int:
        prices = self.qcc.get(name)
        if not prices or len(prices) != 1:
            raise KeyError(f"expected one per-file price for {name!r}, got {prices}")
        return next(iter(prices))


def number(value: int) -> str:
    return f"{value:,}"


def dollars(value: float) -> str:
    return f"${value:,.2f}".replace(".00", "")


def table(table_id: str | None, headers: list[str], rows: list[list[str]],
          right_from: int | None = 1) -> str:
    attr = f" id='{table_id}'" if table_id else ""
    out = [HEADER + f'<table class="qc-table table"{attr}>', "    <thead>", "        <tr>"]
    out += [f"            <th>{h}</th>" for h in headers]
    out += ["        </tr>", "    </thead>", "    <tbody>"]
    for row in rows:
        out += ["        <tr>"] + [f"            <td>{c}</td>" for c in row] + ["        </tr>"]
    out += ["    </tbody>", "</table>"]
    if table_id and right_from is not None:
        out += ["", "<style>",
                f"#{table_id} td:nth-child(n+{right_from + 1}),",
                f"#{table_id} th:nth-child(n+{right_from + 1}) {{",
                "    text-align: right;", "}", "</style>"]
    return "\n".join(out) + "\n"


def resolution_rows(prices: Prices, pattern: str, labels: list) -> list[list[str]]:
    rows = []
    for label in labels:
        label, members = label if isinstance(label, tuple) else (label, [label])
        tiers = {tuple(prices.yearly(pattern.format(m))) for m in members}
        if len(tiers) != 1:
            raise ValueError(f"{label}: {members} no longer share one price; split the row")
        rows.append([label] + [number(v) for v in tiers.pop()])
    return rows


def security_master(prices: Prices, market: str) -> list[int]:
    return prices.yearly(f"{market} Security Master by QuantConnect")


def total_rows(prices: Prices, lines: list[tuple]) -> list[list[str]]:
    rows, history, updates = [], 0, 0
    for label, package, name in lines:
        if name.startswith("sm:"):
            h = u = security_master(prices, name[3:])[0]
        else:
            h, u = prices.yearly(name.format("History"))[0], prices.yearly(name.format("Updates"))[0]
        history, updates = history + h, updates + u
        rows.append([label, package, dollars(h), f"{dollars(u)}/year"])
    if len(rows) > 1:
        rows.append(["Total", "", dollars(history), f"{dollars(updates)}/year"])
    return rows


def page_tables(prices: Prices, page: str, spec: dict) -> dict[str, str]:
    tiers_header = ["Resolution"] + TIER_LABELS
    out = {}
    if "bulk" in spec:
        out["bulk-download"] = table(f"{page}-bulk-download-price", tiers_header,
                                     resolution_rows(prices, *spec["bulk"]))
    if "updates" in spec:
        out["bulk-updates"] = table(f"{page}-bulk-update-price", tiers_header,
                                    resolution_rows(prices, *spec["updates"]))
    if "flat_updates" in spec:
        pattern, labels = spec["flat_updates"]
        tiers = {tuple(prices.yearly(pattern.format(r))) for r in labels}
        if len(tiers) != 1:
            raise ValueError(f"{page}: updates no longer cost the same for every resolution")
        out["bulk-updates"] = table(f"{page}-bulk-update-price", ["Tier", "Price ($/Year)"],
                                    [[t, number(v)] for t, v in zip(TIER_LABELS, tiers.pop())])
    if "same_for_all" in spec:
        pattern = spec["same_for_all"]
        prices_seen = {(tuple(prices.yearly(pattern.format(r, "History"))),
                        tuple(prices.yearly(pattern.format(r, "Updates"))))
                       for r in ("Second", "Minute", "Hour", "Daily")}
        if len(prices_seen) != 1 or len(set(prices_seen.pop()[0])) != 1:
            raise ValueError(f"{page}: bulk no longer costs the same for every resolution and tier")
    if "universe" in spec:
        name = spec["universe"]
        history, updates = prices.yearly(name.format("History")), prices.yearly(name.format("Updates"))
        out["universe"] = table(f"{page}-universe-bulk-price", ["Tier", "Historical", "Updates"],
                                [[t, number(h), number(u)]
                                 for t, h, u in zip(TIER_LABELS, history, updates)])
    out["bulk-total"] = table(None, ["Dataset", "Package", "Historical", "Updates"],
                              total_rows(prices, spec["total"]))
    if "per_file" in spec:
        rows = []
        for label, files, name in spec["per_file"]:
            qcc = prices.per_file(name)
            rows.append([label, files, f"{number(qcc)} QCC = {dollars(qcc / 100)} USD"])
        out["per-file"] = table(None, ["Resolution", "File Format", "Cost per file"], rows)
    return out


def storage_table(data: dict) -> str:
    rows = [["0.05", number(STORAGE_FILES[0.05]), "0"]]
    for it in sorted(data.get("objectStorage") or [], key=lambda i: i["storage"]):
        size = it["storage"] / 2**30
        size = int(size) if size == int(size) else size
        rows.append([number(size), number(STORAGE_FILES[size]), number(it["price"]["monthly"])])
    intro = (
        "<p>The Object Store is available to paid organizations. Paid organizations get 50 MB of "
        "free storage in the Object Store and can subscribe to more storage space. Storage "
        "subscriptions add capacity only; they don't enable <a href=\"/docs/v2/cloud-platform/"
        "object-store#04-Download-Files\">downloading files</a>. The following table shows the "
        "cost of the supported storage sizes:</p>\n\n")
    body = table("storage-sizes-table", ["Storage Size (GB)", "Storage Files (-)", "Monthly Cost ($)"],
                 rows, right_from=0)
    return HEADER + intro + body.replace(HEADER, "", 1)


def main() -> None:
    data = catalog()
    org_id = quote_org()
    rows = price_rows(datasets(None), org_id, 4)
    prices = Prices(data, rows, file_rules(org_id))

    written = {}
    for market, slug in (("US Equity", "us-equity"), ("US Futures", "us-futures")):
        written[RESOURCES / f"datasets/{slug}-security-master-price.html"] = table(
            f"{slug}-security-master-price", ["Tier", "Price ($/Year)"],
            [[t, number(v)] for t, v in zip(TIER_LABELS, security_master(prices, market))])
    for page, spec in PAGES.items():
        for name, html in page_tables(prices, page, spec).items():
            written[RESOURCES / f"datasets/lean-cli-prices/{page}-{name}.html"] = html
    written[RESOURCES / "object-store/storage-sizes.html"] = storage_table(data)

    for path, html in written.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(html, encoding="utf-8", newline="\n")
        print(f"wrote {path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
