from pathlib import Path
import os
import shutil

root_dir = "Resources/datasets/market-hours/"
target_dir = "02 Writing Algorithms/03 Securities/99 Asset Classes/"
conversions = {
    "future": "07 Futures/04 Market Hours",
    "cfd": "11 CFD/04 Market Hours"
}
page_order = {
    "introduction.html": 0,
    "pre-market-hours.html": 1,
    "market-opening-hours.html": 2,
    "post-market-hours.html": 3,
    "holidays.html": 4,
    "early-closes.html": 5,
    "late-opens.html": 6,
    "time-zone.html": 7
}

for dir, target in conversions.items():
    path = Path(f'{root_dir}{dir}')
    subdirs = [str(subdir.name).upper() for subdir in path.iterdir() if subdir.is_dir()]
    
    i = 11
    
    for subdir in subdirs:
        if subdir == "FXCM": continue
        
        market_dir = path / subdir.lower()
        output_dir = Path(f'{target_dir}{target}/{i:02} {subdir}')
        if os.path.exists(output_dir):
            shutil.rmtree(output_dir)
        output_dir.mkdir(parents=True, exist_ok=True)
        
        j = 1

        for html in sorted((market_dir / 'generic').glob('**/*.html'), key=lambda x: page_order[x.name]):
            page_name = str(html.name).replace('-', ' ').title()
            
            codes = open(html).read()
            with open(output_dir / f'{j:02} {page_name.replace("Html", "html")}', 'w', encoding='utf-8') as html_file:
                html_file.write(codes)
            
            j += 1
            
        empty_table = f"""<table class="table qc-table table-reflow">
<thead>
<tr><th>Symbol</th><th>Contract</th></tr>
</thead>
<tbody>
<tr><td><a href="{subdir.lower()}">Generic</a></td><td>generic</td></tr>
</tbody>
</table>"""
            
        codes = open(f'{root_dir}{dir.title()}.html').read().split(f'<h4>{subdir.upper()}</h4>')[-1].split('</table>')[0].split('</h4>')[-1] + '</table>'
        with open(output_dir / f'{j:02} Specific Assets.html', 'w', encoding='utf-8') as html_file:
            html_file.write("""<!-- Code generated by market-hour-convertor.py -->
<p>Below table shows specific symbols with their special market hours.</p>
""")
            html_file.write(codes.replace(empty_table, f'<p>All assets in the {subdir.lower()} follow the above stated market hours.</p>').replace(f'<tr><td><a href="{subdir.lower()}">Generic</a></td><td>generic</td></tr>', ''))
            
        assets_subdirs = [str(subdir.name) for subdir in market_dir.iterdir() if subdir.is_dir() and subdir.name != "generic"]
        
        k = 11
        
        for asset in assets_subdirs:
            contract_name = asset.replace("__", " ").replace("_", " ").upper()
            raw_asset_dir = market_dir / asset.lower()
            asset_dir = output_dir/ f'{k:02} {contract_name}'
            asset_dir.mkdir(parents=True, exist_ok=True)
        
            n = 1
            
            for html in sorted(raw_asset_dir.glob('**/*.html'), key=lambda x: page_order[x.name]):
                page_name = str(html.name).replace('-', ' ').title()

                codes = open(html).read()
                with open(asset_dir / f'{n:02} {page_name.replace("Html", "html")}', 'w', encoding='utf-8') as html_file:
                    html_file.write(codes)
                
                n += 1
                
            k += 1
            
        i += 1