<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "AverageTrueRange";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/average-true-range.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>