<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AverageTrueRange';
$helperName = 'AverageTrueRange';
$pyHelperName = 'average_true_range';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("TrueRange");
$pythonProperties = array("True_range");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>