<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "PercentagePriceOscillator";
$indicatorVariable = "ppo";
$csharpProperties = array("Fast","Slow","Signal","Histogram");
$pythonProperties = array("fast","slow","signal","histogram");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>