<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'Momersion';
$helperName = 'MOMERSION';
$pyHelperName = 'momersion';
$helperArguments = 'symbol, 10, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>