<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "AdvanceDeclineRatio";
$indicatorVariable = "adr";
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>