<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AdvanceDeclineRatio';
$helperName = 'ADR';
$pyHelperName = 'adr';
$helperArguments = '[symbol, reference]';
$hasReference = true;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>