<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'SuperTrend';
$helperName = 'STR';
$pyHelperName = 'str';
$helperArguments = 'symbol, 20, 2, MovingAverageType.Wilders';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>