<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'McClellanOscillator';
$helperName = 'MOSC';
$helperArguments = '["SPY", "QQQ"]';
$properties = array("EMAFast","EMASlow","ADDifference");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '"QQQ"]';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mc-clellan-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>