<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "FisherTransform";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/fisher-transform.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>