<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'KlingerVolumeOscillator';
$helperName = 'KlingerVolumeOscillator';
$pyHelperName = 'klinger_volume_oscillator';
$helperArguments = 'symbol';
$properties = array("Signal");
$pyProperties = array("signal");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'klinger-volume-oscillator';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>