<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "CommodityChannelIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/commodity-channel-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>