<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "RateOfChangePercent";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/rate-of-change-percent.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>