<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'AdvanceDeclineVolumeRatio';
$helperName = 'ADVR';
$helperArguments = '["SPY", "QQQ"]';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '"QQQ"]';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'advance-decline-volume-ratio';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>