<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'AbsolutePriceOscillator';
$helperName = 'APO';
$helperArguments = '"SPY", 10, 2';
$properties = array("Fast","Slow","Signal","Histogram");
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 2';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'absolute-price-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>