<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'EaseOfMovementValue';
$helperName = 'EMV';
$helperArguments = 'symbol, 1, 10000';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '1, 10000';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'ease-of-movement-value';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>