<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'MeanAbsoluteDeviation';
$helperName = 'MAD';
$pyHelperName = 'mad';
$helperArguments = 'symbol, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Mean");
$pythonProperties = array("mean");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>