<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'AccelerationBands';
$helperName = 'AccelerationBands';
$pyHelperName = 'acceleration_bands';
$helperArguments = 'symbol';
$properties = array("MiddleBand","UpperBand","LowerBand");
$pyProperties = array("middle_band","upper_band","lower_band");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'acceleration-bands';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>