<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'StochasticRelativeStrengthIndex';
$helperName = 'SRSI';
$pyHelperName = 'srsi';
$helperArguments = 'symbol, 14, 14, 3, 3';
$properties = array("K","D");
$pyProperties = array("k","d");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '14, 14, 3, 3';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'stochastic-relative-strength-index';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>