<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = true;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'ArmsIndex';
$helperName = 'TRIN';
$helperArguments = '[symbol, reference]';
$properties = array("ADRatio","ADVRatio");
$otherProperties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '""';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'arms-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>