<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "RelativeVigorIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/relative-vigor-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>