<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'AdvanceDeclineVolumeRatio';
$helperName = 'AdvanceDeclineVolumeRatio';
$pyHelperName = 'advance_decline_volume_ratio';
$helperArguments = 'symbol';
$properties = array();
$pyProperties = array();
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'advance-decline-volume-ratio';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>