<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "AdvanceDeclineVolumeRatio";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/advance-decline-volume-ratio.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>