<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'MovingAverageConvergenceDivergence';
$helperName = 'MovingAverageConvergenceDivergence';
$pyHelperName = 'moving_average_convergence_divergence';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Fast","Slow","Signal","Histogram");
$pythonProperties = array("fast","slow","signal","histogram");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>