<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "ChaikinMoneyFlow";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/chaikin-money-flow.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>