<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "AverageDirectionalMovementIndexRating";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/average-directional-movement-index-rating.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>