<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'RelativeVigorIndex';
$helperName = 'RVI';
$pyHelperName = 'rvi';
$helperArguments = 'symbol, 20, MovingAverageType.Simple';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Signal");
$pythonProperties = array("signal");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>