<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = 'CandlestickPatterns.';
$typeName = 'BeltHold';
$helperName = 'BeltHold';
$pyHelperName = 'belt_hold';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>