<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'AverageTrueRange';
$helperName = 'ATR';
$helperArguments = 'symbol, 20, MovingAverageType.Simple';
$properties = array("TrueRange");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20, MovingAverageType.Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'average-true-range';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>