<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "AverageTrueRange";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/average-true-range.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>