<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'TimeProfile';
$helperName = 'TP';
$helperArguments = '"SPY", 3, 0.70, 0.05';
$properties = array("VolumePerPrice","ProfileHigh","ProfileLow","POCPrice","POCVolume","ValueAreaVolume","ValueAreaHigh","ValueAreaLow");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '3, 0.70, 0.05';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'time-profile';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>