<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'CoppockCurve';
$helperName = 'CC';
$pyHelperName = 'cc';
$helperArguments = 'symbol, 11, 14, 10';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>