<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'SchaffTrendCycle';
$helperName = 'STC';
$pyHelperName = 'stc';
$helperArguments = 'symbol, 5, 10, 20, MovingAverageType.Exponential';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>