<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "AwesomeOscillator";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/awesome-oscillator.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>