<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AwesomeOscillator';
$helperName = 'AO';
$pyHelperName = 'ao';
$helperArguments = 'symbol, 10, 20, MovingAverageType.Simple';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("SlowAo","FastAo");
$pythonProperties = array("slow_ao","fast_ao");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>