<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'EaseOfMovementValue';
$helperName = 'EMV';
$pyHelperName = 'emv';
$helperArguments = 'symbol, 1, 10000';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>