<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = "BollingerBands";
$helperName = "BB";
$helperCall = 'BB("SPY", 30, 2)';
$properties = array("MiddleBand", "MiddleBand", "LowerBand");
$updateParameterType = "date/time pair";
$constructorCall = 'BollingerBands(30, 2)';
$updateParameterValue = 'bar.EndTime, bar.Close';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>