<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'MoneyFlowIndex';
$helperName = 'MoneyFlowIndex';
$pyHelperName = 'money_flow_index';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("PositiveMoneyFlow","NegativeMoneyFlow");
$pythonProperties = array("positive_money_flow","negative_money_flow");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>