<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = false;
$typeName = 'Delay';
$helperName = 'Delay';
$helperArguments = 'SPY';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = 'SPY';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'delay';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>