<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'EaseOfMovementValue';
$helperName = 'EMV';
$helperArguments = '"SPY", 1, 10000';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '1, 10000';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'ease-of-movement-value';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>