<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'PercentagePriceOscillator';
$helperName = 'PercentagePriceOscillator';
$pyHelperName = 'percentage_price_oscillator';
$helperArguments = 'symbol';
$properties = array("Fast","Slow","Signal","Histogram");
$pyProperties = array("fast","slow","signal","histogram");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'percentage-price-oscillator';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>