<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'SwissArmyKnife';
$helperName = 'SWISS';
$helperArguments = 'symbol, 20, 0.2, SwissArmyKnifeTool.Gauss';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '20, 0.2, SwissArmyKnifeTool.Gauss';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'swiss-army-knife';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>