<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "AwesomeOscillator";
$indicatorVariable = "ao";
$csharpProperties = array("SlowAo","FastAo");
$pythonProperties = array("slow_ao","fast_ao");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>