<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'HeikinAshi';
$helperName = 'HeikinAshi';
$helperArguments = 'symbol';
$properties = array("Open","High","Low","Close","Volume");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'heikin-ashi';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>