<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'MoneyFlowIndex';
$helperName = 'MFI';
$helperArguments = 'symbol, 20';
$properties = array("PositiveMoneyFlow","NegativeMoneyFlow");
$pyProperties = array("positive_money_flow","negative_money_flow");
$otherProperties = array("PreviousTypicalPrice");
$otherPyProperties = array("previous_typical_price");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'money-flow-index';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>