<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'TrueStrengthIndex';
$helperName = 'TSI';
$helperArguments = '"SPY", 20, 10, 5';
$properties = array("Signal");
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '20, 10, 5';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'true-strength-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>