<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "TrueStrengthIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/true-strength-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>