<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "SchaffTrendCycle";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/schaff-trend-cycle.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>