<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'ArmsIndex';
$helperName = 'TRIN';
$helperArguments = '[self.symbol, Symbol.Create';
$properties = array("ADRatio","ADVRatio");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'Symbol.Create';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'arms-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>