<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "KaufmanAdaptiveMovingAverage";
$indicatorVariable = "kama";
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>