<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "PremierStochasticOscillator";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/premier-stochastic-oscillator.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>