<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "Gamma";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/gamma.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>