<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'ArnaudLegouxMovingAverage';
$helperName = 'ALMA';
$helperArguments = '"SPY", 10, 6, 0.85';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 6, 0.85';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'arnaud-legoux-moving-average';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>