<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "KaufmanEfficiencyRatio";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/kaufman-efficiency-ratio.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>