<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'VolumeWeightedAveragePriceIndicator';
$helperName = 'VolumeWeightedAveragePriceIndicator';
$pyHelperName = 'volume_weighted_average_price_indicator';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>