<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "StalledPattern";
$indicatorVariable = "stalledpattern";
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>