<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hadReference = true;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'Correlation';
$helperName = 'C';
$helperArguments = 'symbol, reference, 20, correlationType=CorrelationType.Pearson';
$properties = array();
$otherProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '"", symbol, reference, 20, correlationType=CorrelationType.Pearson';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'correlation';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>