<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "MovingAverageConvergenceDivergence";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/moving-average-convergence-divergence.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>