<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ZigZag';
$helperName = 'ZZ';
$pyHelperName = 'zz';
$helperArguments = 'symbol, 0.05, 1';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("HighPivot","LowPivot","PivotType");
$pythonProperties = array("high_pivot","low_pivot","pivot_type");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>