<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'AccelerationBands';
$helperName = 'ABANDS';
$helperArguments = '"SPY", 10, 4, MovingAverageType.Simple';
$properties = array("MiddleBand","UpperBand","LowerBand");
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 4, MovingAverageType.Simple';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'acceleration-bands';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>