<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "RateOfChangeRatio";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/rate-of-change-ratio.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>