<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "AutoRegressiveIntegratedMovingAverage";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/auto-regressive-integrated-moving-average.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>