<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'AccumulationDistributionOscillator';
$helperName = 'ADOSC';
$helperArguments = '"SPY", 10, 2';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '10, 2';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'accumulation-distribution-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>