<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'HilbertTransform';
$helperName = 'HT';
$pyHelperName = 'ht';
$helperArguments = 'symbol, 7, 0.635, 0.338';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("InPhase","Quadrature");
$pythonProperties = array("in_phase","quadrature");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>