<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "KaufmanAdaptiveMovingAverage";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/kaufman-adaptive-moving-average.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>