<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "MomentumPercent";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/momentum-percent.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>