<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "McGinleyDynamic";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/mc-ginley-dynamic.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>