<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ArnaudLegouxMovingAverage';
$helperName = 'ALMA';
$helperArguments = 'symbol, 10, 6, 0.85';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>