<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'ThreeLineStrike';
$helperName = 'ThreeLineStrike';
$helperArguments = 'symbol';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'symbol';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'three-line-strike';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>