<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "AugenPriceSpike";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/augen-price-spike.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>