<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'TargetDownsideDeviation';
$helperName = 'TDD';
$pyHelperName = 'tdd';
$helperArguments = 'symbol, 50';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>