<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "LeastSquaresMovingAverage";
$indicatorVariable = "lsma";
$csharpProperties = array("Intercept","Slope");
$pythonProperties = array("intercept","slope");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>