<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "HilbertTransform";
$indicatorVariable = "ht";
$csharpProperties = array("InPhase","Quadrature");
$pythonProperties = array("in_phase","quadrature");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>