<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'MesaAdaptiveMovingAverage';
$helperName = 'MesaAdaptiveMovingAverage';
$pyHelperName = 'mesa_adaptive_moving_average';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Fama");
$pythonProperties = array("fama");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>