<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "RegressionChannel";
$indicatorVariable = "rc";
$csharpProperties = array("LinearRegression","UpperChannel","LowerChannel","Intercept","Slope");
$pythonProperties = array("linear_regression","upper_channel","lower_channel","intercept","slope");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>