<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "SqueezeMomentum";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/squeeze-momentum.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>