<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "DeMarkerIndicator";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/de-marker-indicator.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>