<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'SwissArmyKnife';
$helperName = 'SWISS';
$helperArguments = '"SPY", 20, 0.2, Gauss';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '20, 0.2, Gauss';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'swiss-army-knife';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>