<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "SwissArmyKnife";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/swiss-army-knife.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>