<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "EaseOfMovementValue";
$indicatorVariable = "emv";
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>