<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "OnBalanceVolume";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/on-balance-volume.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>