<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "ArmsIndex";
$indicatorVariable = "trin";
$csharpProperties = array("ADRatio","ADVRatio");
$pythonProperties = array("ad_ratio","adv_ratio");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>