<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ArmsIndex';
$helperName = 'ArmsIndex';
$pyHelperName = 'arms_index';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("ADRatio","ADVRatio");
$pythonProperties = array("ad_ratio","adv_ratio");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>