<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ArmsIndex';
$helperName = 'TRIN';
$helperArguments = '[symbol, reference]';
$hasReference = true;
$isOptionIndicator = false;
$csharpProperties = array("ADRatio","ADVRatio");
$pythonProperties = array("ad_ratio","adv_ratio");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>