<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hadReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = 'CandlestickPatterns.';
$typeName = 'IdenticalThreeCrows';
$helperName = 'IdenticalThreeCrows';
$helperArguments = 'symbol';
$properties = array();
$otherProperties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'identical-three-crows';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>