<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'RelativeStrengthIndex';
$helperName = 'RSI';
$helperArguments = '"SPY", 14';
$properties = array("AverageLoss","AverageGain");
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '14';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'relative-strength-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>