<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'PivotPointsHighLow';
$helperName = 'PPHL';
$helperArguments = '"SPY", 10, 10, 100';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 10, 100';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'pivot-points-high-low';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>