<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'WilderSwingIndex';
$helperName = 'SI';
$helperArguments = '"SPY", 20';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'wilder-swing-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>