<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hadReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'CommodityChannelIndex';
$helperName = 'CCI';
$helperArguments = 'symbol, 20, MovingAverageType.Simple';
$properties = array("TypicalPriceAverage","TypicalPriceMeanDeviation");
$otherProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '20, MovingAverageType.Simple';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'commodity-channel-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>