<div class="section-example-container"><pre class="csharp"># Name                               Version
Accord                               3.6.0
Accord.Audio                         3.6.0
Accord.Fuzzy                         3.6.0
Accord.Genetic                       3.6.0
Accord.MachineLearning               3.6.0
Accord.MachineLearning.GPL           3.6.0
Accord.Math                          3.6.0
Accord.Statistics                    3.6.0
CNTK.CPUOnly                         2.8.0-rc0.dev20200201
Catalyst                             1.0.31087
Catalyst.Models.English              1.0.30952
CloneExtensions                      1.3.0
CoinAPI.WebSocket.V1                 1.6.7
Common.Logging                       3.4.1
Common.Logging.Core                  3.4.1
CsvHelper                            19.0.0
Deedle                               2.1.0
DotNetZip                            1.16.0
DynamicInterop                       0.9.1
FSharp.Core                          4.5.2
Google.OrTools                       9.4.1874
IQFeed.CSharpApiClient               2.5.1
LaunchDarkly.EventSource             3.3.2
LibTopoART                           0.96.0
MathNet.Filtering                    0.7.0
MathNet.Filtering.Kalman             0.7.0
MathNet.Numerics                     4.15.0
MathNet.Spatial                      0.6.0
McMaster.Extensions.CommandLineUtils 2.6.0
Microsoft.Data.Analysis              0.19.1
Microsoft.IO.RecyclableMemoryStream  2.2.0
Microsoft.ML                         1.7.1
Microsoft.ML.CpuMath                 1.7.1
Microsoft.ML.DataView                1.7.1
Microsoft.ML.Ensemble                0.19.1
Microsoft.ML.FastTree                1.7.1
Microsoft.ML.LightGbm                1.7.1
Microsoft.ML.Mkl.Components          1.7.1
Microsoft.ML.OnnxRuntime             1.12.1
Microsoft.ML.TensorFlow              1.7.1
Microsoft.ML.TimeSeries              1.7.1
Microsoft.NET.Test.Sdk               16.9.4
Microsoft.TestPlatform.ObjectModel   16.9.4
Moq                                  4.16.1
NUnit                                3.13.3
NUnit3TestAdapter                    4.2.1
NetMQ                                4.0.1.6
Newtonsoft.Json                      12.0.3
NodaTime                             3.0.5
NumSharp                             0.30.0
Plotly.NET                           3.0.1
Plotly.NET.Interactive               3.0.2
QLNet                                1.12.0
QuantConnect.pythonnet               2.0.17
R.NET                                1.9.0
RestSharp                            106.12.0
SharpLearning.AdaBoost               0.31.8
SharpLearning.Common.Interfaces      0.31.8
SharpLearning.Containers             0.31.8
SharpLearning.CrossValidation        0.31.8
SharpLearning.DecisionTrees          0.31.8
SharpLearning.Ensemble               0.31.8
SharpLearning.FeatureTransformations 0.31.8
SharpLearning.GradientBoost          0.31.8
SharpLearning.InputOutput            0.31.8
SharpLearning.Metrics                0.31.8
SharpLearning.Neural                 0.31.8
SharpLearning.Optimization           0.31.8
SharpLearning.RandomForest           0.31.8
SharpLearning.XGBoost                0.31.8
SharpNeatLib                         2.4.4
SharpZipLib                          1.3.3
System.ComponentModel.Composition    6.0.0
TensorFlow.Keras                     0.7.0
TensorFlow.NET                       0.70.1
fasterflect                          3.0.0
protobuf-net                         3.0.29
</pre><pre class="python"># Name                       Version
_libgcc_mutex                0.1
_openmp_mutex                5.1
absl-py                      1.2.0
aeppl                        0.0.33
aesara                       2.7.9
aiosignal                    1.2.0
alembic                      1.8.1
anyio                        3.6.1
appdirs                      1.4.4
arch                         5.3.1
argon2-cffi                  21.3.0
argon2-cffi-bindings         21.2.0
arviz                        0.12.1
asn1crypto                   1.5.1
astropy                      5.1
asttokens                    2.0.8
astunparse                   1.6.3
attrs                        22.1.0
autograd                     1.4
autopage                     0.5.1
autoray                      0.3.2
ax-platform                  0.2.6
babel                        2.10.3
backcall                     0.2.0
backports-zoneinfo           0.2.1
bayesian-optimization        1.2.0
beautifulsoup4               4.11.1
bleach                       5.0.1
blis                         0.7.8
botorch                      0.6.6
brotlipy                     0.7.0
bzip2                        1.0.8
ca-certificates              2022.6.15
cachetools                   5.2.0
catalogue                    2.0.8
catboost                     1.0.6
certifi                      2022.6.15
cffi                         1.15.1
cftime                       1.6.1
chardet                      4.0.0
charset-normalizer           2.0.4
click                        8.0.4
cliff                        4.0.0
cloudpickle                  2.1.0
cmaes                        0.8.2
cmd2                         2.4.2
cmdstanpy                    1.0.4
colorlog                     6.6.0
colorlover                   0.3.0
conda                        4.14.0
conda-env                    2.6.0
conda-package-handling       1.8.1
cons                         0.4.5
convertdate                  2.4.0
copulae                      0.7.7
copulas                      0.7.0
creme                        0.6.1
cryptography                 37.0.1
cufflinks                    0.17.3
cvxopt                       1.3.0
cvxpy                        1.2.1
cycler                       0.11.0
cymem                        2.0.6
cython                       0.29.30
dask                         2022.8.1
deap                         1.3.3
debugpy                      1.5.1
decorator                    5.1.1
defusedxml                   0.7.1
deprecated                   1.2.13
dgl                          0.9.0
dill                         0.3.5.1
distlib                      0.3.5
distributed                  2022.8.1
dm-tree                      0.1.7
docutils                     0.19
dtw-python                   1.2.2
dx                           0.1.22
ecos                         2.0.10
entrypoints                  0.4
ephem                        4.1.3
etils                        0.7.1
etuples                      0.3.5
exchange-calendars           4.2
executing                    0.10.0
fastai                       2.7.7
fastai2                      0.0.30
fastcore                     1.5.21
fastdownload                 0.0.7
fastjsonschema               2.16.1
fastprogress                 1.0.3
fasttext                     0.9.2
featuretools                 0.18.1
filelock                     3.8.0
findiff                      0.9.2
flatbuffers                  1.12
fonttools                    4.36.0
frozendict                   2.3.4
frozenlist                   1.3.1
fsspec                       2022.7.1
future                       0.18.2
gast                         0.4.0
gensim                       4.2.0
gluonts                      0.7.7
google-auth                  2.11.0
google-auth-oauthlib         0.4.6
google-pasta                 0.2.0
gplearn                      0.4.2
gpytorch                     1.8.1
greenlet                     1.1.2
grpcio                       1.43.0
gym                          0.25.1
gym-notices                  0.0.8
h2o                          3.36.1.4
h5py                         3.7.0
heapdict                     1.0.1
hijri-converter              2.2.4
hmmlearn                     0.2.7
holidays                     0.15
hopcroftkarp                 1.2.5
hyperopt                     0.2.7
idna                         3.3
importlib-metadata           4.12.0
importlib-resources          5.9.0
ipykernel                    6.15.1
ipython                      8.4.0
ipython-genutils             0.2.0
ipywidgets                   8.0.0rc1
jax                          0.3.16
jaxlib                       0.3.15
jedi                         0.18.1
jinja2                       3.1.2
joblib                       1.1.0
json5                        0.9.10
jsonschema                   4.9.1
jupyter-client               7.3.4
jupyter-core                 4.11.1
jupyter-server               1.18.1
jupyterlab                   3.4.4
jupyterlab-pygments          0.2.2
jupyterlab-server            2.15.0
jupyterlab-widgets           3.0.2
keras                        2.9.0
keras-preprocessing          1.1.2
keras-rl                     0.4.2
kiwisolver                   1.4.4
kmapper                      2.0.1
korean-lunar-calendar        0.2.1
langcodes                    3.3.0
lazy-loader                  0.1rc2
ld_impl_linux-64             2.38
libclang                     14.0.6
libedit                      3.1.20170329
libffi                       3.3
libgcc-ng                    11.2.0
libgomp                      11.2.0
libstdcxx-ng                 8.2.0
libuuid                      1.0.3
lightgbm                     3.3.2
littleutils                  0.2.2
llvmlite                     0.39.0
locket                       1.0.0
logical-unification          0.4.5
lunarcalendar                0.0.9
lxml                         4.9.1
mako                         1.2.1
markdown                     3.4.1
markupsafe                   2.1.1
matplotlib                   3.5.3
matplotlib-inline            0.1.6
minikanren                   1.0.3
mistune                      2.0.4
mmh3                         2.5.1
mpi                          1.0
mpi4py                       3.1.3
mplfinance                   0.12.9b1
mpmath                       1.2.1
msgpack                      1.0.4
multipledispatch             0.6.0
murmurhash                   1.0.8
mxnet                        1.9.1
nbclassic                    0.4.3
nbclient                     0.6.6
nbconvert                    7.0.0
nbeats-keras                 1.7.0
nbeats-pytorch               1.6.0
nbformat                     5.4.0
ncurses                      6.3
nest-asyncio                 1.5.5
netcdf4                      1.6.0
networkx                     2.8.6
neural-tangents              0.6.0
ninja                        1.10.2.3
nltk                         3.7
notebook                     6.4.12
notebook-shim                0.1.0
numba                        0.56.0
numpy                        1.22.4
oauthlib                     3.2.0
openmpi                      4.1.4
openssl                      1.1.1q
opt-einsum                   3.3.0
optuna                       2.10.1
osqp                         0.6.2.post5
outdated                     0.2.1
packaging                    21.3
pandas                       1.4.3
pandas-flavor                0.3.0
pandas-market-calendars      3.5
pandocfilters                1.5.0
parso                        0.8.3
partd                        1.3.0
pathy                        0.6.2
patsy                        0.5.2
pbr                          5.10.0
pennylane                    0.25.1
pennylane-lightning          0.25.0
persim                       0.3.1
pexpect                      4.8.0
pickleshare                  0.7.5
pillow                       9.2.0
pingouin                     0.5.2
pip                          22.2.2
pkgutil-resolve-name         1.3.10
platformdirs                 2.5.2
plotly                       5.9.0
pmdarima                     1.8.5
ppscore                      1.2.0
preshed                      3.0.7
prettytable                  3.3.0
prometheus-client            0.14.1
prompt-toolkit               3.0.30
property-cached              1.6.4
prophet                      1.1
protobuf                     3.19.4
psutil                       5.9.1
ptvsd                        4.3.2
ptyprocess                   0.7.0
pulp                         2.6.0
pure-eval                    0.2.2
py4j                         0.10.9.7
pyaml                        21.10.1
pyasn1                       0.4.8
pyasn1-modules               0.2.8
pybind11                     2.10.0
pycosat                      0.6.3
pycparser                    2.21
pydantic                     1.9.2
pydevd-pycharm               201.8538.36
pyerfa                       2.0.0.1
pygments                     2.13.0
pykalman                     0.9.5
pyluach                      2.0.0
pymc                         4.1.4
pymeeus                      0.5.11
pynndescent                  0.5.7
pyopenssl                    22.0.0
pyparsing                    3.0.9
pyperclip                    1.8.2
pyportfolioopt               1.5.1
pyrb                         1.0.1
pyro-api                     0.1.2
pyro-ppl                     1.8.1
pyrsistent                   0.18.1
pysocks                      1.7.1
python                       3.8.13
python-dateutil              2.8.2
python-graphviz              0.8.4
python_abi                   3.8
pytz                         2022.2.1
pytz-deprecation-shim        0.1.0.post0
pywavelets                   1.3.0
pyyaml                       6.0
pyzmq                        23.2.1
qdldl                        0.1.5.post2
quadprog                     0.1.11
quantecon                    0.5.3
quantlib                     1.27
rauth                        0.7.3
ray                          1.13.0
readline                     8.1.2
regex                        2022.8.17
requests                     2.28.1
requests-oauthlib            1.3.1
retworkx                     0.11.0
ripser                       0.6.4
riskfolio-lib                3.3.0
riskparityportfolio          0.3
rpy2                         3.5.3
rsa                          4.9
ruamel_yaml                  0.15.100
ruptures                     1.1.7
scikit-learn                 1.0.2
scikit-learn-extra           0.2.0
scikit-multiflow             0.5.3
scikit-optimize              0.9.0
scikit-tda                   1.0.0
scipy                        1.8.1
scs                          3.2.0
sdeint                       0.3.0
seaborn                      0.11.2
semantic-version             2.10.0
send2trash                   1.8.0
setuptools                   61.2.0
setuptools-git               1.2
simpy                        4.0.1
six                          1.16.0
sklearn-json                 0.1.0
sktime                       0.13.1
smart-open                   5.2.1
sniffio                      1.2.0
sortedcontainers             2.4.0
soupsieve                    2.3.2.post1
spacy                        3.4.1
spacy-legacy                 3.0.10
spacy-loggers                1.0.3
sqlalchemy                   1.4.40
sqlite                       3.39.2
srsly                        2.4.4
ssm                          0.0.1
stack-data                   0.4.0
statsmodels                  0.13.2
stevedore                    4.0.0
sympy                        1.10.1
ta                           0.10.1
ta-lib                       0.4.18
tabulate                     0.8.10
tadasets                     0.0.4
tblib                        1.7.0
tenacity                     8.0.1
tensorboard                  2.9.1
tensorboard-data-server      0.6.1
tensorboard-plugin-wit       1.8.1
tensorflow                   2.9.1
tensorflow-estimator         2.9.0
tensorflow-io-gcs-filesystem 0.26.0
termcolor                    1.1.0
terminado                    0.15.0
tf2jax                       0.3.1
thinc                        8.1.0
threadpoolctl                3.1.0
tigramite                    5.0.0.1
tinycss2                     1.1.1
tk                           8.6.12
toml                         0.10.2
toolz                        0.12.0
torch                        1.12.1
torch-cluster                1.6.0
torch-geometric              2.0.4
torch-scatter                2.0.9
torch-sparse                 0.6.14
torch-spline-conv            1.2.1
torchvision                  0.13.1
tornado                      6.1
tqdm                         4.64.0
traitlets                    5.3.0
tsfresh                      0.15.1
tslearn                      0.5.2
tweepy                       4.10.0
typeguard                    2.13.3
typer                        0.4.2
typing-extensions            4.3.0
tzdata                       2022.2
tzlocal                      4.2
ujson                        5.4.0
umap-learn                   0.5.3
urllib3                      1.26.11
virtualenv                   20.16.3
wasabi                       0.10.1
wcwidth                      0.2.5
webencodings                 0.5.1
websocket-client             1.3.3
werkzeug                     2.2.2
wheel                        0.37.1
widgetsnbextension           4.0.2
wrapt                        1.14.1
xarray                       2022.6.0
xarray-einstats              0.3.0
xgboost                      1.6.1
xlsxwriter                   3.0.3
xz                           5.2.5
yaml                         0.2.5
zict                         2.2.0
zipp                         3.8.1
zlib                         1.2.12
</pre></div>