<div class="section-example-container">
<pre class="python">
about-time                              4.2.1
absl-py                                 2.3.1
accelerate                              1.10.1
adagio                                  0.2.6
aiohappyeyeballs                        2.6.1
aiohttp                                 3.13.0
aiosignal                               1.4.0
aiosqlite                               0.21.0
alembic                                 1.16.5
alive-progress                          3.3.0
alphalens-reloaded                      0.4.6
altair                                  5.5.0
annotated-types                         0.7.0
anyio                                   4.11.0
aplr                                    10.15.0
appdirs                                 1.4.4
apricot-select                          0.6.1
arch                                    7.2.0
argon2-cffi                             25.1.0
argon2-cffi-bindings                    25.1.0
arrow                                   1.3.0
arviz                                   0.22.0
astropy                                 7.1.0
astropy-iers-data                       0.2025.10.6.0.35.25
asttokens                               3.0.0
astunparse                              1.6.3
async-lru                               2.0.5
attrs                                   25.4.0
Authlib                                 1.6.5
autograd                                1.8.0
autograd-gamma                          0.5.0
autokeras                               2.0.0
autoray                                 0.7.2
ax-platform                             1.1.2
babel                                   2.17.0
banks                                   2.2.0
bayesian-optimization                   3.1.0
beartype                                0.22.2
beautifulsoup4                          4.14.2
behave                                  1.3.3
bleach                                  6.2.0
blinker                                 1.9.0
blis                                    1.2.1
blosc2                                  3.10.0
bokeh                                   3.6.3
botorch                                 0.15.1
bottle                                  0.13.4
Bottleneck                              1.6.0
build                                   1.3.0
cachetools                              6.2.0
captum                                  0.8.0
catalogue                               2.0.10
catboost                                1.2.8
causal-conv1d                           1.5.2
causalml                                0.15.5
cbor                                    1.0.0
cesium                                  0.12.1
chardet                                 5.2.0
check-shapes                            1.1.1
chronos-forecasting                     1.5.3
clarabel                                0.11.1
click                                   8.2.1
clikit                                  0.6.2
cloudpathlib                            0.23.0
cloudpickle                             3.1.1
clr-loader                              0.1.6
cma                                     4.4.0
cmaes                                   0.12.0
cmdstanpy                               1.2.5
colorama                                0.4.6
colorcet                                3.1.0
coloredlogs                             15.0.1
colorlog                                6.9.0
colorlover                              0.3.0
colour                                  0.1.5
comm                                    0.2.3
confection                              0.1.5
cons                                    0.4.7
contourpy                               1.3.3
control                                 0.10.2
copulae                                 0.7.9
copulas                                 0.12.3
coreforecast                            0.0.16
cramjam                                 2.11.0
crashtest                               0.3.1
creme                                   0.6.1
cucumber-expressions                    18.0.1
cucumber-tag-expressions                7.0.0
cuda-bindings                           12.9.2
cuda-pathfinder                         1.3.0
cuda-python                             12.9.2
cufflinks                               0.17.3
cupy-cuda12x                            13.6.0
curl_cffi                               0.13.0
cvxopt                                  1.3.2
cvxportfolio                            1.5.1
cvxpy                                   1.7.3
cycler                                  0.12.1
cyclopts                                3.24.0
cymem                                   2.0.11
Cython                                  3.1.4
darts                                   0.38.0
dash                                    2.9.3
dash-core-components                    2.0.0
dash-html-components                    2.0.0
dash-table                              5.0.0
dash_cytoscape                          1.0.2
dask                                    2025.7.0
databricks-sdk                          0.67.0
dataclasses-json                        0.6.7
datasets                                3.6.0
deap                                    1.4.3
debugpy                                 1.6.7.post1
decorator                               5.2.1
deepmerge                               2.0
defusedxml                              0.7.1
Deprecated                              1.2.18
DESlib                                  0.3.7
dgl                                     2.1.0
diastatic-malt                          2.15.2
dill                                    0.3.8
dimod                                   0.12.21
dirtyjson                               1.0.8
diskcache                               5.6.3
distributed                             2025.7.0
dm-tree                                 0.1.9
dnspython                               2.8.0
docker                                  7.1.0
docstring_parser                        0.17.0
docutils                                0.22.2
DoubleML                                0.10.1
dropstackframe                          0.1.1
dtreeviz                                2.2.2
dtw-python                              1.5.3
dwave-cloud-client                      0.14.0
dwave-gate                              0.3.4
dwave-hybrid                            0.6.14
dwave-inspector                         0.5.5
dwave-inspectorapp                      0.3.3
dwave-ocean-sdk                         9.0.0
dwave-optimization                      0.6.4
dwave-preprocessing                     0.6.10
dwave-samplers                          1.6.0
dwave-system                            1.33.0
dwave_networkx                          0.8.18
econml                                  0.16.0
ecos                                    2.0.14
einops                                  0.8.1
einx                                    0.3.0
email-validator                         2.3.0
EMD-signal                              1.6.4
empyrical-reloaded                      0.5.12
en-core-web-md                          3.8.0
en-core-web-sm                          3.8.0
et_xmlfile                              2.0.0
etuples                                 0.3.10
exceptiongroup                          1.3.0
exchange_calendars                      4.11.1
executing                               2.2.1
faiss-cpu                               1.12.0
Farama-Notifications                    0.0.4
fastai                                  2.8.4
fastai2                                 0.0.30
fastapi                                 0.118.2
fastcore                                1.8.12
fastdownload                            0.0.7
fasteners                               0.20
fastjsonschema                          2.21.2
fastmcp                                 2.10.6
fastparquet                             2024.11.0
fastprogress                            1.0.3
fastrlock                               0.8.3
fasttext                                0.9.3
fasttransform                           0.0.2
feature_engine                          1.9.3
featuretools                            1.31.0
filelock                                3.20.0
filetype                                1.2.0
filterpy                                1.4.5
findiff                                 0.12.1
FixedEffectModel                        0.0.5
FlagEmbedding                           1.3.5
Flask                                   3.1.2
flatbuffers                             25.9.23
fonttools                               4.60.1
forestci                                0.6
formulaic                               1.2.1
fqdn                                    1.5.1
frozenlist                              1.8.0
fs                                      2.4.16
fsspec                                  2025.3.0
fugue                                   0.9.1
future                                  1.0.0
fuzzy-c-means                           1.7.2
gast                                    0.6.0
gatspy                                  0.3
gensim                                  4.3.3
gevent                                  25.9.1
gitdb                                   4.0.12
GitPython                               3.1.45
gluonts                                 0.16.2
google-auth                             2.41.1
google-genai                            1.41.0
google-pasta                            0.2.0
gpflow                                  2.10.0
gpytorch                                1.14
graphemeu                               0.7.2
graphene                                3.4.3
graphql-core                            3.2.6
graphql-relay                           3.2.0
graphviz                                0.21
greenlet                                3.2.4
griffe                                  1.14.0
grpcio                                  1.75.1
gunicorn                                23.0.0
gym                                     0.26.2
gym-notices                             0.1.0
gymnasium                               1.1.1
h11                                     0.16.0
h2o                                     3.46.0.7
h5netcdf                                1.6.4
h5py                                    3.14.0
hf-xet                                  1.1.10
hmmlearn                                0.3.3
holidays                                0.82
holoviews                               1.20.2
homebase                                1.0.1
hopcroftkarp                            1.2.5
http-sf                                 1.0.4
httpcore                                1.0.9
httpstan                                4.13.0
httpx                                   0.28.1
httpx-sse                               0.4.2
huggingface-hub                         0.35.3
humanfriendly                           10.0
hurst                                   0.0.5
hvplot                                  0.12.1
hyperopt                                0.2.7
ibm-cloud-sdk-core                      3.24.2
ibm-platform-services                   0.69.0
iisignature                             0.24
ijson                                   3.4.0
imageio                                 2.37.0
imbalanced-learn                        0.14.0
immutabledict                           4.2.1
importlib_metadata                      8.7.0
importlib_resources                     6.5.2
iniconfig                               2.1.0
injector                                0.22.0
inscriptis                              2.6.0
interface-meta                          1.3.0
interpret                               0.7.2
interpret-core                          0.7.2
ipykernel                               6.30.1
ipympl                                  0.9.7
ipython                                 9.6.0
ipython_pygments_lexers                 1.1.1
ipywidgets                              8.1.7
ir_datasets                             0.5.11
isoduration                             20.11.0
itsdangerous                            2.2.0
jax                                     0.7.1
jaxlib                                  0.7.1
jaxtyping                               0.3.3
jedi                                    0.19.2
Jinja2                                  3.1.6
jiter                                   0.11.0
joblib                                  1.5.2
json5                                   0.12.1
jsonpath-ng                             1.7.0
jsonpointer                             2.1
jsonschema                              4.25.1
jsonschema-specifications               2025.9.1
jupyter                                 1.1.1
jupyter-console                         6.6.3
jupyter-events                          0.12.0
jupyter-lsp                             2.3.0
jupyter-resource-usage                  1.2.0
jupyter_ai                              2.31.6
jupyter_ai_magics                       2.31.6
jupyter_bokeh                           4.0.5
jupyter_client                          8.6.3
jupyter_core                            5.8.1
jupyter_server                          2.17.0
jupyter_server_terminals                0.5.3
jupyterlab                              4.4.9
jupyterlab_pygments                     0.3.0
jupyterlab_server                       2.27.3
jupyterlab_widgets                      3.0.15
kagglehub                               0.3.13
kaleido                                 0.2.1
KDEpy                                   1.1.12
keras                                   3.11.3
keras-hub                               0.22.2
keras-nlp                               0.22.2
keras-rl                                0.4.2
keras-tcn                               3.5.6
keras-tuner                             1.4.7
kiwisolver                              1.4.9
kmapper                                 2.1.0
korean-lunar-calendar                   0.3.1
kt-legacy                               1.0.5
langchain                               0.3.27
langchain-community                     0.3.31
langchain-core                          0.3.78
langchain-text-splitters                0.3.11
langcodes                               3.5.0
langsmith                               0.4.33
language_data                           1.3.0
lark                                    1.3.0
lazy_loader                             0.4
lazypredict                             0.2.16
libclang                                18.1.1
lifelines                               0.30.0
lightgbm                                4.6.0
lightning                               2.5.5
lightning-utilities                     0.15.2
lightweight-charts                      2.1
lime                                    0.2.0.1
line_profiler                           5.0.0
linear-operator                         0.6
lingam                                  1.11.0
linkify-it-py                           2.0.3
livelossplot                            0.5.6
llama-cloud                             0.1.35
llama-cloud-services                    0.6.54
llama-index                             0.12.42
llama-index-agent-openai                0.4.12
llama-index-cli                         0.4.4
llama-index-core                        0.12.42
llama-index-embeddings-openai           0.3.1
llama-index-indices-managed-llama-cloud 0.8.0
llama-index-llms-openai                 0.4.7
llama-index-multi-modal-llms-openai     0.5.1
llama-index-program-openai              0.3.2
llama-index-question-gen-openai         0.3.1
llama-index-readers-file                0.4.8
llama-index-readers-llama-parse         0.4.0
llama-parse                             0.6.54
llvmlite                                0.44.0
locket                                  1.0.0
logical-unification                     0.4.6
loguru                                  0.7.3
lxml                                    6.0.2
lz4                                     4.4.4
Mako                                    1.3.10
mamba-ssm                               2.2.5+cu12torch2.8cxx11abiTRUE
MAPIE                                   1.1.0
marisa-trie                             1.3.1
Markdown                                3.9
markdown-it-py                          4.0.0
MarkupSafe                              3.0.3
marshmallow                             3.26.1
matplotlib                              3.8.4
matplotlib-inline                       0.1.7
mcp                                     1.16.0
mdit-py-plugins                         0.5.0
mdurl                                   0.1.2
mgarch                                  0.3.0
miniKanren                              1.0.5
minorminer                              0.2.19
mistune                                 3.1.4
ml_dtypes                               0.5.3
mlflow                                  3.4.0
mlflow-skinny                           3.4.0
mlflow-tracing                          3.4.0
mlforecast                              1.0.2
mljar-scikit-plot                       0.3.12
mljar-supervised                        1.1.18
mlxtend                                 0.23.4
mmh3                                    2.5.1
modin                                   0.37.1
mplfinance                              0.12.10b0
mpmath                                  1.3.0
msgpack                                 1.1.1
multidict                               6.7.0
multipledispatch                        1.0.0
multiprocess                            0.70.16
multitasking                            0.0.12
murmurhash                              1.0.13
mypy_extensions                         1.1.0
namex                                   0.1.0
narwhals                                2.7.0
nbclient                                0.10.2
nbconvert                               7.16.6
nbformat                                5.10.4
ndindex                                 1.10.0
nest-asyncio                            1.6.0
networkx                                3.5
neuralforecast                          3.1.2
neuralprophet                           0.9.0
nfoursid                                1.0.2
ngboost                                 0.5.6
ninja                                   1.13.0
nixtla                                  0.7.0
nltk                                    3.9.2
nolds                                   0.6.2
nose                                    1.3.7
notebook                                7.4.7
notebook_shim                           0.2.4
numba                                   0.61.2
numba-cuda                              0.14.1
numdifftools                            0.9.41
numerapi                                2.20.8
numexpr                                 2.13.1
numpy                                   1.26.4
nvidia-cublas-cu12                      12.8.4.1
nvidia-cuda-cccl-cu12                   12.9.27
nvidia-cuda-cupti-cu12                  12.8.90
nvidia-cuda-nvcc-cu12                   12.9.86
nvidia-cuda-nvrtc-cu12                  12.8.93
nvidia-cuda-runtime-cu12                12.8.90
nvidia-cuda-runtime-cu13                0.0.0a0
nvidia-cudnn-cu12                       9.10.2.21
nvidia-cufft-cu12                       11.3.3.83
nvidia-cufile-cu12                      1.13.1.3
nvidia-curand-cu12                      10.3.9.90
nvidia-cusolver-cu12                    11.7.3.90
nvidia-cusparse-cu12                    12.5.8.93
nvidia-cusparselt-cu12                  0.7.1
nvidia-nccl-cu12                        2.27.3
nvidia-nvjitlink-cu12                   12.8.93
nvidia-nvtx-cu12                        12.8.90
oauthlib                                3.3.1
onnx                                    1.19.0
onnxmltools                             1.14.0
onnxruntime                             1.23.0
openai                                  1.109.1
openapi-pydantic                        0.5.1
opencv-contrib-python-headless          4.11.0.86
openpyxl                                3.1.5
opentelemetry-api                       1.37.0
opentelemetry-proto                     1.37.0
opentelemetry-sdk                       1.37.0
opentelemetry-semantic-conventions      0.58b0
opt_einsum                              3.4.0
optree                                  0.17.0
optuna                                  4.5.0
optuna-integration                      4.5.0
orjson                                  3.11.3
ormsgpack                               1.7.0
ortools                                 9.12.4544
osqp                                    1.0.4
overrides                               7.7.0
packaging                               25.0
pandas                                  2.3.3
pandas_flavor                           0.7.0
pandas_market_calendars                 5.1.1
pandocfilters                           1.5.1
panel                                   1.7.5
param                                   2.2.1
parse                                   1.20.2
parse_type                              0.6.6
parso                                   0.8.5
partd                                   1.4.2
pastel                                  0.2.1
pathos                                  0.2.9
patsy                                   1.0.1
peewee                                  3.17.3
peft                                    0.17.1
penaltymodel                            1.3.0
pennylane                               0.42.3
pennylane_lightning                     0.42.0
persim                                  0.3.8
pexpect                                 4.9.0
pgmpy                                   1.0.0
pillow                                  11.3.0
pingouin                                0.5.5
platformdirs                            4.5.0
plotly                                  5.24.1
plucky                                  0.4.3
pluggy                                  1.6.0
plum-dispatch                           2.5.8
ply                                     3.11
pmdarima                                2.0.4
polars                                  1.34.0
polars-runtime-32                       1.34.0
pomegranate                             1.1.2
POT                                     0.9.6.post1
pox                                     0.3.6
ppft                                    1.7.7
pprofile                                2.2.0
preshed                                 3.0.10
progressbar2                            4.5.0
prometheus_client                       0.23.1
prompt_toolkit                          3.0.52
propcache                               0.4.1
prophet                                 1.1.7
protobuf                                5.29.5
proxy_tools                             0.1.0
psutil                                  7.1.0
psy                                     0.0.1
ptvsd                                   4.3.2
ptyprocess                              0.7.0
PuLP                                    3.3.0
pure_eval                               0.2.3
py-cpuinfo                              9.0.0
py-heat                                 0.0.6
py-heat-magic                           0.0.2
py4j                                    0.10.9.9
py_lets_be_rational                     1.0.1
py_vollib                               1.0.1
pyaml                                   25.7.0
pyarrow                                 19.0.1
pyasn1                                  0.6.1
pyasn1_modules                          0.4.2
pybind11                                3.0.1
pydantic                                2.12.0
pydantic-settings                       2.11.0
pydantic_core                           2.41.1
pydevd-pycharm                          231.9225.15
PyDMD                                   2025.8.1
pydotplus                               2.0.2
pyerfa                                  2.0.1.5
pyfolio-reloaded                        0.9.9
pygam                                   0.10.1
Pygments                                2.19.2
PyJWT                                   2.10.1
pykalman                                0.10.2
pylev                                   1.4.0
pyluach                                 2.3.0
pymannkendall                           1.4.3
pymc                                    5.25.1
pymdptoolbox                            4.0b3
pymoo                                   0.6.1.5
pynndescent                             0.5.13
pyod                                    2.0.5
pyomo                                   6.9.4
pyparsing                               3.2.5
pypdf                                   5.9.0
pyperclip                               1.11.0
pyportfolioopt                          1.5.6
pyproject_hooks                         1.2.0
PyQt6                                   6.9.1
PyQt6-Qt6                               6.9.2
PyQt6_sip                               13.10.2
pyre-extensions                         0.0.32
pyro-api                                0.1.2
pyro-ppl                                1.9.1
pysimdjson                              6.0.2
pyspnego                                0.12.0
pystan                                  3.10.0
pytensor                                2.31.7
pytest                                  8.4.2
pytest-runner                           6.0.1
python-dateutil                         2.9.0.post0
python-dotenv                           1.1.1
python-json-logger                      4.0.0
python-multipart                        0.0.20
python-statemachine                     2.5.0
python-utils                            3.9.1
pytorch-forecasting                     1.4.0
pytorch-ignite                          0.5.2
pytorch-lightning                       2.5.2
pytorch-tabnet                          4.1.0
pytz                                    2025.2
pyvers                                  0.1.0
pyvinecopulib                           0.6.5
pyviz_comms                             3.0.6
PyWavelets                              1.9.0
pywebview                               6.0
PyYAML                                  6.0.3
pyzmq                                   27.1.0
qiskit                                  2.1.2
qiskit-aer                              0.17.2
qiskit-ibm-runtime                      0.41.1
quadprog                                0.1.13
quantecon                               0.10.1
QuantLib                                1.39
QuantStats                              0.0.77
rauth                                   0.7.3
ray                                     2.49.2
Rbeast                                  0.1.23
referencing                             0.36.2
regex                                   2025.9.18
requests                                2.32.5
requests-oauthlib                       2.0.0
requests-toolbelt                       1.0.0
requests_ntlm                           1.3.0
rfc3339-validator                       0.1.4
rfc3986-validator                       0.1.1
rfc3987-syntax                          1.1.0
rich                                    14.2.0
rich-rst                                1.3.1
ripser                                  0.6.12
Riskfolio-Lib                           7.0.1
riskparityportfolio                     0.6.0
river                                   0.21.0
rpds-py                                 0.27.1
rsa                                     4.9.1
ruptures                                1.1.10
rustworkx                               0.17.1
safetensors                             0.6.2
SALib                                   1.5.1
sb3_contrib                             2.7.0
schema                                  0.7.7
scikeras                                0.13.0
scikit-base                             0.12.6
scikit-image                            0.22.0
scikit-learn                            1.6.1
scikit-learn-extra                      0.3.0
scikit-optimize                         0.10.2
scikit-tda                              1.1.1
scipy                                   1.13.1
scipy-openblas32                        0.3.30.0.2
scs                                     3.2.8
sdeint                                  0.3.0
seaborn                                 0.13.2
semopy                                  2.3.11
Send2Trash                              1.8.3
sentence-transformers                   5.1.1
sentencepiece                           0.2.1
setuptools-scm                          9.2.0
shap                                    0.48.0
Shimmy                                  2.0.0
simplejson                              3.20.2
simpy                                   4.1.1
sismic                                  1.6.10
six                                     1.17.0
skfolio                                 0.7.0
skl2onnx                                1.19.1
sklearn-json                            0.1.0
sktime                                  0.39.0
slicer                                  0.0.8
smart_open                              7.3.1
smmap                                   5.0.2
sniffio                                 1.3.1
sortedcontainers                        2.4.0
soupsieve                               2.8
spacy                                   3.8.7
spacy-legacy                            3.0.12
spacy-loggers                           1.0.5
sparse                                  0.17.0
SQLAlchemy                              2.0.43
sqlparse                                0.5.3
srsly                                   2.5.1
sse-starlette                           3.0.2
stable_baselines3                       2.7.0
stack-data                              0.6.3
stanio                                  0.5.1
starlette                               0.48.0
statsforecast                           2.0.2
statsmodels                             0.14.5
stevedore                               5.5.0
stochastic                              0.6.0
stockstats                              0.6.5
stopit                                  1.1.2
striprtf                                0.0.26
stumpy                                  1.13.0
sweetviz                                2.3.1
sympy                                   1.14.0
ta                                      0.11.0
TA-Lib                                  0.6.7
tables                                  3.10.2
tabulate                                0.9.0
tadasets                                0.2.1
tblib                                   3.1.0
tenacity                                9.1.2
tensorboard                             2.19.0
tensorboard-data-server                 0.7.2
tensorboardX                            2.6.4
tensordict                              0.10.0
tensorflow                              2.19.1
tensorflow-io-gcs-filesystem            0.37.1
tensorflow-probability                  0.25.0
tensorflow-text                         2.19.0
tensorflow_decision_forests             1.12.0
tensorly                                0.9.0
tensorrt                                10.13.3.9
tensorrt_cu13                           10.13.3.9
tensorrt_cu13_bindings                  10.13.3.9
tensorrt_cu13_libs                      10.13.3.9
tensortrade                             1.0.3
termcolor                               3.1.0
terminado                               0.18.1
tf2jax                                  0.3.7
tf2onnx                                 1.16.1
tf_keras                                2.19.0
thinc                                   8.3.4
threadpoolctl                           3.6.0
thundergbm                              0.3.17
tifffile                                2025.10.4
tigramite                               5.2.8.2
tiktoken                                0.12.0
tinycss2                                1.4.0
tinygrad                                0.11.0
tokenizers                              0.22.1
tomlkit                                 0.13.3
toolz                                   0.12.1
torch                                   2.8.0
torch-geometric                         2.6.1
torch_cluster                           1.6.3
torch_scatter                           2.1.2
torch_sparse                            0.6.18
torch_spline_conv                       1.2.2
torchdata                               0.11.0
torchmetrics                            1.8.2
torchrl                                 0.10.0
torchvision                             0.23.0
tornado                                 6.5.2
TPOT                                    0.12.2
traitlets                               5.14.3
transformers                            4.57.0
transitions                             0.9.3
trec-car-tools                          2.6
triad                                   0.9.8
triton                                  3.4.0
tsfel                                   0.2.0
tsfresh                                 0.20.2
tslearn                                 0.6.4
tweepy                                  4.16.0
typer                                   0.9.4
typer-config                            1.4.2
types-python-dateutil                   2.9.0.20251008
typing-inspect                          0.9.0
typing-inspection                       0.4.2
typing_extensions                       4.15.0
tzdata                                  2025.2
uc-micro-py                             1.0.3
umap-learn                              0.5.9.post2
unlzw3                                  0.2.3
update-checker                          0.18.0
uri-template                            1.3.0
urllib3                                 2.5.0
utilsforecast                           0.2.14
uvicorn                                 0.37.0
wadler_lindig                           0.1.7
warc3-wet                               0.2.5
warc3-wet-clueweb09                     0.2.5
wasabi                                  1.1.3
wcwidth                                 0.2.14
weasel                                  0.4.1
webargs                                 8.7.0
webcolors                               24.11.1
webencodings                            0.5.1
websocket-client                        1.9.0
websockets                              15.0.1
Werkzeug                                3.1.3
widgetsnbextension                      4.0.14
woodwork                                0.31.0
wrapt                                   1.17.3
wurlitzer                               3.1.1
x-transformers                          2.8.2
xarray                                  2025.9.1
xarray-einstats                         0.9.1
xgboost                                 3.0.5
xlrd                                    2.0.2
xlsxwriter                              3.2.9
xxhash                                  3.6.0
xyzservices                             2025.4.0
yarl                                    1.22.0
ydf                                     0.13.0
yellowbrick                             1.5
yfinance                                0.2.66
zict                                    3.0.0
zipp                                    3.23.0
zlib-state                              0.1.10
zope.event                              5.1
zope.interface                          8.0.1
</pre><pre class="csharp">
Accord                               3.6.0
Accord.Fuzzy                         3.6.0
Accord.MachineLearning               3.6.0
Accord.Math                          3.6.0
Accord.Statistics                    3.6.0
CloneExtensions                      1.3.0
Common.Logging                       3.4.1
Common.Logging.Core                  3.4.1
CsvHelper                            19.0.0
Deedle                               2.1.0
DotNetZip                            1.16.0
DynamicInterop                       0.9.1
fasterflect                          3.0.0
MathNet.Numerics                     5.0.0
McMaster.Extensions.CommandLineUtils 2.6.0
Microsoft.IO.RecyclableMemoryStream  3.0.1
Microsoft.NET.Test.Sdk               16.9.4
Microsoft.TestPlatform.ObjectModel   16.9.4
Moq                                  4.16.1
NetMQ                                4.0.1.6
Newtonsoft.Json                      13.0.2
NodaTime                             3.0.5
NUnit                                4.2.2
NUnit3TestAdapter                    4.6.0
protobuf-net                         3.1.3
QLNet                                1.13.1
QuantConnect.pythonnet               2.0.48
RestSharp                            106.12.0
SharpZipLib                          1.3.3
System.ComponentModel.Composition    6.0.0
<? if ($cloudPlatform) { ?>
Accord.Audio                         3.6.0
Accord.Genetic                       3.6.0
Accord.MachineLearning.GPL           3.6.0
Castle.Core                          5.2.1
Catalyst                             1.0.54164
Catalyst.Models.English              1.0.30952
CNTK.CPUOnly                         2.8.0-rc0.dev20200201
csnumerics                           1.0.2
Google.OrTools                       9.12.4544
LibTopoART                           0.98.1
MathNet.Filtering                    0.7.0
MathNet.Filtering.Kalman             0.7.0
MathNet.Spatial                      0.6.0
Microsoft.Data.Analysis              0.22.2
Microsoft.ML                         4.0.2
Microsoft.ML.CpuMath                 4.0.2
Microsoft.ML.DataView                4.0.2
Microsoft.ML.Ensemble                0.22.2
Microsoft.ML.FastTree                4.0.2
Microsoft.ML.LightGbm                4.0.2
Microsoft.ML.Mkl.Components          4.0.2
Microsoft.ML.OnnxRuntime             1.23.1
Microsoft.ML.TensorFlow              4.0.2
Microsoft.ML.TimeSeries              4.0.2
NumSharp                             0.30.0
OpenAI                               2.5.0
QuantConnect.PredictNowNET           1.0.4
R.NET                                1.9.0
SciSharp.TensorFlow.Redist           2.16.0
SciSharp.TensorFlow.Redist-Linux-GPU 2.11.1
SharpLearning.AdaBoost               0.31.8
SharpLearning.Common.Interfaces      0.31.8
SharpLearning.Containers             0.31.8
SharpLearning.CrossValidation        0.31.8
SharpLearning.DecisionTrees          0.31.8
SharpLearning.Ensemble               0.31.8
SharpLearning.FeatureTransformations 0.31.8
SharpLearning.GradientBoost          0.31.8
SharpLearning.InputOutput            0.31.8
SharpLearning.Metrics                0.31.8
SharpLearning.Neural                 0.31.8
SharpLearning.Optimization           0.31.8
SharpLearning.RandomForest           0.31.8
SharpLearning.XGBoost                0.31.8
SharpNeatLib                         2.4.4
TensorFlow.Keras                     0.15.0
TensorFlow.NET                       0.150.0
TorchSharp                           0.105.1
<? } ?>
</pre></div>