<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'MoneyFlowIndex';
$helperName = 'MFI';
$helperArguments = 'symbol, 20';
$properties = array("PositiveMoneyFlow","NegativeMoneyFlow");
$otherProperties = array("PreviousTypicalPrice");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'money-flow-index';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>