<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "Alpha";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/alpha.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>