<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'MassIndex';
$helperName = 'MASS';
$helperArguments = 'symbol, 9, 25';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = '9, 25';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mass-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>