<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "CommodityChannelIndex";
$indicatorVariable = "cci";
$csharpProperties = array("TypicalPriceAverage","TypicalPriceMeanDeviation");
$pythonProperties = array("typical_price_average","typical_price_mean_deviation");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>