<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'AverageDirectionalIndex';
$helperName = 'ADX';
$helperArguments = '"SPY", 20';
$properties = array("PositiveDirectionalIndex","NegativeDirectionalIndex");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'average-directional-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>