<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "ConnorsRelativeStrengthIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/connors-relative-strength-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>