<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'DonchianChannel';
$helperName = 'DCH';
$pyHelperName = 'dch';
$helperArguments = 'symbol, 20, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("UpperBand","LowerBand");
$pythonProperties = array("upper_band","lower_band");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>