<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'KaufmanAdaptiveMovingAverage';
$helperName = 'KAMA';
$helperArguments = 'symbol, 20, 10, 20';
$properties = array();
$otherProperties = array();
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '20, 10, 20';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'kaufman-adaptive-moving-average';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>