<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'Beta';
$helperName = 'B';
$pyHelperName = 'b';
$helperArguments = 'symbol, reference, 20';
$hasReference = true;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>