<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "Vega";
$indicatorVariable = "v";
$csharpProperties = array("ImpliedVolatility","RiskFreeRate","DividendYield","Price","OppositePrice","UnderlyingPrice");
$pythonProperties = array("implied_volatility","risk_free_rate","dividend_yield","price","opposite_price","underlying_price");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>