<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'FractalAdaptiveMovingAverage';
$helperName = 'FRAMA';
$pyHelperName = 'frama';
$helperArguments = 'symbol, 20, 198';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>