<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "MassIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/mass-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>