<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'SwissArmyKnife';
$helperName = 'SWISS';
$pyHelperName = 'swiss';
$helperArguments = 'symbol, 20, 0.2, SwissArmyKnifeTool.Gauss';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>