<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'AutoRegressiveIntegratedMovingAverage';
$helperName = 'AutoRegressiveIntegratedMovingAverage';
$pyHelperName = 'auto_regressive_integrated_moving_average';
$helperArguments = 'symbol';
$properties = array();
$pyProperties = array();
$otherProperties = array("HandleExceptions","ArParameters","MaParameters","Intercept","ArResidualError","MaResidualError");
$otherPyProperties = array("handle_exceptions","ar_parameters","ma_parameters","intercept","ar_residual_error","ma_residual_error");
$updateParameterType = 'time/number pair or an <code>IndicatorDataPoint</code>';
$constructorArguments = '';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'auto-regressive-integrated-moving-average';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>