<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AutoRegressiveIntegratedMovingAverage';
$helperName = 'ARIMA';
$pyHelperName = 'arima';
$helperArguments = 'symbol, 1, 1, 1, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>