<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "RateOfChange";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/rate-of-change.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>