<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "RelativeVigorIndex";
$indicatorVariable = "rvi";
$csharpProperties = array("Signal");
$pythonProperties = array("signal");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>