<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'PercentagePriceOscillator';
$helperName = 'PPO';
$helperArguments = '"SPY", 10, 20, MovingAverageType.Simple';
$properties = array("Fast","Slow","Signal","Histogram");
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '10, 20, MovingAverageType.Simple';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = True;
$constructorBox = 'percentage-price-oscillator';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>