<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AccumulationDistributionOscillator';
$helperName = 'ADOSC';
$pyHelperName = 'adosc';
$helperArguments = 'symbol, 10, 2';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>