<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'RelativeMovingAverage';
$helperName = 'RMA';
$pyHelperName = 'rma';
$helperArguments = 'symbol, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("ShortAverage","MediumAverage","LongAverage");
$pythonProperties = array("short_average","medium_average","long_average");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>