<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'RateOfChangePercent';
$helperName = 'ROCP';
$pyHelperName = 'rocp';
$helperArguments = 'symbol, 10';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>