<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'TargetDownsideDeviation';
$helperName = 'TDD';
$helperArguments = '"SPY", 50';
$properties = array();
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '50';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'target-downside-deviation';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>