<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'AverageDirectionalIndex';
$helperName = 'ADX';
$pyHelperName = 'adx';
$helperArguments = 'symbol, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("PositiveDirectionalIndex","NegativeDirectionalIndex");
$pythonProperties = array("positive_directional_index","negative_directional_index");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>