<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "AverageDirectionalIndex";
$indicatorVariable = "adx";
$csharpProperties = array("PositiveDirectionalIndex","NegativeDirectionalIndex");
$pythonProperties = array("positive_directional_index","negative_directional_index");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>