<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'DonchianChannel';
$helperName = 'DCH';
$helperArguments = 'self.symbol, 20, 20';
$properties = array("UpperBand","LowerBand");
$updateParameterType = 'a <code>TradeBar</code>, or <code>QuoteBar</code>';
$constructorArguments = '20, 20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'donchian-channel';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>