<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'MomersionIndicator';
$helperName = 'MomersionIndicator';
$pyHelperName = 'momersion_indicator';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>