<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "SimpleMovingAverage";
$indicatorVariable = "sma";
$csharpProperties = array("RollingSum");
$pythonProperties = array("rolling_sum");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>