<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'Doji';
$helperName = 'Doji';
$helperArguments = 'SPY';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'SPY';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'doji';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>