<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'DerivativeOscillator';
$helperName = 'DO';
$pyHelperName = 'do';
$helperArguments = 'symbol, 14, 5, 3, 9';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>