<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ParabolicStopAndReverse';
$helperName = 'PSAR';
$pyHelperName = 'psar';
$helperArguments = 'symbol, 0.02, 0.02, 0.2';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array();
$pythonProperties = array();
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>