<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'FisherTransform';
$helperName = 'FISH';
$helperArguments = 'symbol, 20';
$properties = array();
$otherProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '20';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'fisher-transform';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>