<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'SimpleMovingAverage';
$helperName = 'SMA';
$pyHelperName = 'sma';
$helperArguments = 'symbol, 20';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("RollingSum");
$pythonProperties = array("rolling_sum");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>