<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'KeltnerChannels';
$helperName = 'KeltnerChannels';
$pyHelperName = 'keltner_channels';
$helperArguments = 'symbol';
$properties = array("MiddleBand","UpperBand","LowerBand","AverageTrueRange");
$pyProperties = array("middle_band","upper_band","lower_band","average_True_range");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'keltner-channels';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>