<!-- Code generated by Indicator-Reference-Code-Generator.py -->
                        
<? include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html"); ?>

<p>You can manually create a <code>VolumeWeightedAveragePriceIndicator</code> indicator, so it doesn’t automatically update. Manual indicators let you update their values with any data you choose. The following reference table describes the <code>VolumeWeightedAveragePriceIndicator</code> constructor.</p>

<? include(DOCS_RESOURCES."/indicators/constructors/vwap.html"); ?>