<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "Stochastic";
$indicatorVariable = "sto";
$csharpProperties = array("FastStoch","StochK","StochD");
$pythonProperties = array("fast_stoch","stoch_k","stoch_d");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>