<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'Vortex';
$helperName = 'Vortex';
$helperArguments = 'symbol';
$properties = array("PlusVortex","MinusVortex");
$pyProperties = array("plus_vortex","minus_vortex");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'vortex';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>