<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'RegressionChannel';
$helperName = 'RC';
$helperArguments = 'symbol, 20, 2';
$properties = array("LinearRegression","UpperChannel","LowerChannel","Intercept","Slope");
$updateParameterType = 'time/number pair, or an <code>IndicatorDataPoint</code>';
$constructorArguments = '20, 2';
$updateParameterValue = 'bar.EndTime, bar.Close';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'regression-channel';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>