SUFFIXES = ["*.html", "*.php"]
# enums or static class, only CAPITALIZE if in form of <enum>.<member>{space or comma character}
ENUMS = [
    'AlphaModelExtensions', 'PortfolioBias', 'with', 'StressSymbols', 'Symbols', 'Equity', 'NotifiedSecurityChanges', 'State', 'State', 
    'ReturnsSymbolDataExtensions', 'DebuggingMethod', 'DebuggerHelper', 'SeriesType', 'BinaryComparisonExtensions', 'ChartType', 'Currencies', 
    'Expiry', 'value', 'Extensions', 'BrokerageEnvironment', 'Language', 'ServerType', 'SecurityType', 'AccountType', 'MarketDataType', 
    'DataFeedEndpoint', 'StoragePermissions', 'TickType', 'DelistingType', 'SplitType', 'Resolution', 'PositionSide', 'OptionRight', 'OptionStyle', 
    'SettlementType', 'AlgorithmStatus', 'SubscriptionTransportMedium', 'WritePolicy', 'Period', 'DataNormalizationMode', 'DataMappingMode', 
    'CashBookUpdateType', 'DeploymentTarget', 'AlgorithmMode', 'DateFormat', 'Exchanges', 'ChannelStatus', 'Globals', 'IsolatorLimitResultProvider',
    'Market', 'OS', 'Parse', 'ScatterMarkerSymbol', 'StringExtensions', 'SymbolCache', 'SymbolRepresentation', 'Time', 'TimeZones', 'TradingDayType', 
    'InsightDirection', 'InsightScoreType', 'InsightType', 'CompileState', 'NodeType', 'OptimizationNodes', 'ProductType', 'BrokerageMessageType', 
    'BrokerageName', 'BrokerageModel', 'FileFormat', 'HistoryExtensions', 'RiskFreeInterestRateModelExtensions', 'SliceExtensions', 
    'SubscriptionDataConfigExtensions', 'FactorFileZipHelper', 'MapFileZipHelper', 'MappingExtensions', 'PriceScalingExtensions', 'Calendar', 
    'CalendarType', 'FilteredIdentityDataConsolidator', 'FxcmSymbolId', 'PlaceHolder', 'IntrinioEconomicDataSources', 'BofAMerrillLynch', 'CBOE', 
    'Commodities', 'ExchangeRates', 'Moodys', 'TradeWeightedUsDollarIndex', 'IntrinioConfig', 'IntrinioDataTransformation', 'Tiingo', 
    'TiingoSymbolMapper', 'StockType', 'StyleBox', 'MorningstarEconomySphereCode', 'MorningstarSectorCode', 'MorningstarIndustryGroupCode', 
    'MorningstarIndustryCode', 'FundamentalProperty', 'Period', 'PeriodAsByte', 'BarDirection', 'DataDictionaryExtensions', 'RenkoType', 
    'FundamentalService', 'UniverseExtensions', 'InsightManager', 'ReadOnlySecurityValuesCollection', 'Insight', 'InsightScore', 'PortfolioTarget', 
    'FuncBenchmark', 'DefaultBrokerageModel', 'AlphaStreamsBrokerageModel', 'AxosBrokerageModel', 'BinanceBrokerageModel', 'BinanceUSBrokerageModel', 
    'BrokerageMessageEvent', 'DefaultBrokerageMessageHandler', 'ExanteBrokerageModel', 'FTXBrokerageModel', 'FxcmBrokerageModel', 
    'CoinbaseBrokerageModel', 'InteractiveBrokersBrokerageModel', 'TradierBrokerageModel', 'TradingTechnologiesBrokerageModel', 
    'WolverineBrokerageModel', 'RBIBrokerageModel', 'BaseCommand', 'BaseCommandHandler', 'FileCommandHandler', 'OrderCommand', 
    'DllNotFoundPythonExceptionInterpreter', 'InvalidTokenPythonExceptionInterpreter', 'KeyErrorPythonExceptionInterpreter', 
    'NoMethodMatchPythonExceptionInterpreter', 'ScheduledEventExceptionInterpreter', 'StackExceptionInterpreter', 
    'UnsupportedOperandPythonExceptionInterpreter', 'IndicatorDataPoint', 'RollingWindow', 'NotificationEmail', 'NotificationJsonConverter', 
    'OptimizerObjectivesCommon', 'Constraint', 'ExtremumJsonConverter', 'Objective', 'Target', 'OptimizationParameterJsonConverter', 
    'OptimizationStepParameter', 'CancelOrderRequest', 'GroupOrderExtensions', 'LimitIfTouchedOrder', 'LimitOrder', 'Order', 'OrderEvent', 
    'OrderRequest', 'OrderResponse', 'OrderTicket', 'StopLimitOrder', 'StopMarketOrder', 'TrailingStopOrder', 'SubmitOrderRequest', 
    'UpdateOrderRequest', 'FeeModel', 'AlphaStreamsFeeModel', 'ExanteFeeModel', 'InteractiveBrokersFeeModel', 'TDAmeritradeFeeModel', 'FillModel', 
    'EquityFillModel', 'DefaultExerciseModel', 'VolumeShareSlippageModel', 'PythonCommon', 'MarginCallModelPythonWrapper', 'PandasConverter', 
    'PandasData', 'PythonInitializer', 'PythonWrapper', 'AlphaRuntimeStatistics', 'Chart', 'ChartPoint', 'Candlestick', 'Currencies', 
    'ExtendedDictionary', 'Extensions', 'Holding', 'AlgorithmControl', 'Isolator', 'Market', 'OS', 'Parse', 'SecurityIdentifier', 'StringExtensions', 
    'Symbol', 'SymbolCache', 'SymbolRepresentation', 'SymbolValueJsonConverter', 'Time', 'TradingCalendar', 'AccountEvent', 'BuyingPowerModel', 
    'PositionGroupBuyingPowerModel', 'Cash', 'CashBook', 'CashBuyingPowerModel', 'DefaultMarginCallModel', 'DynamicSecurityData', 
    'EquityPriceVariationModel', 'ErrorCurrencyConverter', 'FuncSecuritySeeder', 'IdentityCurrencyConverter', 'InitialMarginParameters', 
    'LocalMarketHours', 'MaintenanceMarginParameters', 'MarketHoursDatabase', 'MarketHoursSegment', 'RegisteredSecurityDataTypesProvider', 
    'Security', 'SecurityDatabaseKey', 'SecurityDefinitionSymbolResolver', 'SecurityExchangeHours', 'SecurityHolding', 'SecurityManager', 
    'SecurityPortfolioManager', 'SecurityService', 'SecurityTransactionManager', 'SymbolProperties', 'SymbolPropertiesDatabase', 'PositionGroup', 
    'OptimizationStatus', 'GroupOrderExtensions', 'IndiaProductType', 'OrderError', 'OrderExtensions', 'OrderField', 'OrderRequestStatus', 
    'OrderRequestType', 'OrderResponseErrorCode', 'OrderSizing', 'OrderType', 'OrderDirection', 'OrderPosition', 'OrderStatus', 'FeeModelExtensions', 
    'HistoryResultType', 'PacketType', 'PythonInitializer', 'PythonWrapper', 'BuyingPowerModelExtensions', 'MarginCallModel', 'MarginInterestRateModel',
    'OrderProviderExtensions', 'SecurityInitializer', 'SecurityProviderExtensions', 'SecuritySeeder', 'MarketHoursState', 'FutureExpirationCycles', 
    'FutureFilterUniverseEx', 'Futures', 'Grains', 'Currencies', 'Energies', 'Financials', 'Indices', 'Forestry', 'Meats', 'Metals', 'Softs', 'Dairy', 
    'FuturesExpiryUtilityFunctions', 'FuturesListings', 'FutureSymbol', 'FutureOptionSymbol', 'FuturesOptionsExpiryFunctions', 
    'FuturesOptionsSymbolMappings', 'FuturesOptionsUnderlyingMapper', 'IndexSymbol', 'IndexOptionSymbol', 'AdjustmentType', 'OptionFilterUniverseEx', 
    'OptionPriceModels', 'OptionStrategies', 'OptionSymbol', 'ConstantOptionStrategyLegReferenceValue', 'OptionStrategyDefinitions', 
    'PredicateTargetValue', 'PortfolioMarginChart', 'PositionExtensions', 'PositionGroupBuyingPowerModelExtensions', 'PositionGroupExtensions', 
    'VolatilityModel', 'VolatilityModelExtensions', 'PerformanceMetrics', 'StatisticsBuilder', 'TradeDirection', 'FillGroupingMethod', 
    'FillMatchingMethod', 'ComparisonOperator', 'ComparisonOperatorTypes', 'Match', 'CurrencyPairUtil', 'DisposableExtensions', 'EnumeratorExtensions',
    'ExpressionBuilder', 'LeanData', 'LinqExtensions', 'ObjectActivator', 'OptionPayoff', 'ReaderWriterLockSlimExtensions', 'Ref',
    'SecurityExtensions', 'StreamReaderExtensions', 'Validate', 'RegularExpression', 'XElementExtensions', 'TokenBucket', 'Compression', 
    'ApplicationParser', 'Config', 'LeanArgumentParser', 'OptimizerArgumentParser', 'ReportArgumentParser', 'ToolboxArgumentParser', 'Initializer', 
    'FillForwardResolutionOperation', 'SubscriptionDataSourceReader', 'SubscriptionUtils', 'CorporateEventEnumeratorFactory', 'ScheduledEventFactory',
    'BaseSetupHandler', 'CorrelationType', 'IndicatorExtensions', 'IndicatorStatus', 'MovingAverageType', 'MovingAverageTypeExtensions', 
    'OptionPricingModelType', 'PivotPointType', 'SwissArmyKnifeTool', 'CandleSettingType', 'CandleRangeType', 'CandleColor', 'CandleSettings', 
    'LogHandlerExtensions', 'Log', 'LogType', 'WhoCalledMe', 'CrisisEvent', 'DeedleUtil', 'Metrics', 'ReportKey', 'ResultsUtil', 'Rolling', 
    'AlgorithmRunner', 'SymbolsKey', 'Symbols', 'TestExtensions', 'TestGlobals', 'TestProcess', 'SecuritySeedData', 'Option', 
    'PerformanceBenchmarkAlgorithms', 'TestHelper', 'PythonTestingUtils', 'PythonWrapperTests', 'DataProcessor', 'StreamProvider', 
    'TemporaryPathProvider', 'AlgoSeekFuturesProgram', 'CryptoiqDownloaderProgram', 'DukascopyDownloaderProgram', 'IVolatilityEquityConverterProgram', 
    'KaikoDataConverterProgram', 'KrakenDownloaderProgram', 'NseMarketDataConverterProgram', 'DataDensity', 'RandomDataGeneratorProgram', 
    'YahooDownloaderProgram','TimeInForce','Universe','Field'
]
SWAPS = {
    "ETF": "Etf",
    "FIGI": "Figi",
    "ID": "Id",
    "BinanceUS": "BinanceUs",
    "PERatio": "PeRatio",
    "CrankNicolsonFD": "CrankNicolsonFd",
    "OECDRecessionIndicators": "OecdRecessionIndicators",
    "QuantConnectBrokerage": "QuantconnectBrokerage",
    "TDAmeritrade": "TdAmeritrade",
    "VWAP": "Vwap",
    "OneWeekBasedOnUSD": "OneWeekBasedOnUsd",
    "SP500EMini": "SP500E_MINI",
    "CrudeOilWTI": "CRUDE_OIL_WTI",
    "Gold": "GOLD",
}
EXCEPTIONS = [
    "ElementTree",
    "SMA",
    "EMA",
    "QuantConnect.Data",
    "QuantConnect.Data.UniverseSelection",
    "QuantConnect.DataSource",
    "QuantConnect.Python",
    "QuantConnect.symbol",
    "GaussianHMM",
    "ht_auth.SetToken",
    "nn.Module",
    "nn.Sequential",
    "nn.Linear",
    "nn.Flatten",
    "nn.ReLU",
    "nn.MSELoss",
    "gym.Env",
    "gym.spaces.Discrete",
    "gym.spaces.Box",
    "tf.Session",
    "tf.Variable",
    "tf.train.AdamOptimizer",
    "json_format.MessageToJson",
    "json_format.Parse",
    "tf.MetaGraphDef",
    "xgb.DMatrix",
    "Selection.OptionUniverseSelectionModel",
    "Selection.FutureUniverseSelectionModel",
    "pd.DataFrame",
    "pd.Series",
    "pd.MultiIndex",
    "opt.TargetWeights",
    "opt.MaxGrossExposure",
    "opt.DollarNeutral",
    "go.Candlestick",
    "go.Layout",
    "go.layout.Title",
    "go.Figure",
    "go.Scatter",
    "go.scatter.Marker",
    "Newtonsoft.Json",
    "System.Collections.Generic",
    "JsonConvert.SerializeObject",
    "Calculators.TaxesCalculator"
]