<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "AverageDirectionalIndex";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/average-directional-index.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>