<!-- Code generated by indicator_reference_code_generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$hasAutomaticIndicatorHelper = true;
$typeName = 'OnBalanceVolume';
$helperName = 'OBV';
$helperArguments = 'self.symbol';
$properties = array();
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'self.symbol';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'on-balance-volume';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>