<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<?
$typeName = "AccumulationDistribution";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/accumulation-distribution.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>