<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "PivotPointsHighLow";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/pivot-points-high-low.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>