<!-- Code generated by indicator_reference_code_generator.py -->
<?
$typeName = "Stochastic";
$imageSource = "https://cdn.quantconnect.com/docs/i/writing-algorithms/indicators/supported-indicators/stochastic.png";
include(DOCS_RESOURCES."/indicators/visualization.php");
?>