<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "WilliamsPercentR";
$indicatorVariable = "wilr";
$csharpProperties = array("Maximum","Minimum");
$pythonProperties = array("maximum","minimum");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>