<!-- Code generated by Indicator-Reference-Code-Generator.py -->
<? 
include(DOCS_RESOURCES."/qcalgorithm-api/_method_container.html");

$typeName = 'McClellanSummationIndex';
$helperName = 'McClellanSummationIndex';
$helperArguments = 'SPY';
$properties = array("McClellanOscillator");
$updateParameterType = 'a <code>TradeBar</code>';
$constructorArguments = 'SPY';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'mc-clellan-summation-index';
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>