<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$hasReference = false;
$hasAutomaticIndicatorHelper = true;
$helperPrefix = '';
$typeName = 'ChandeKrollStop';
$helperName = 'CKS';
$pyHelperName = 'cks';
$helperArguments = 'symbol, 10, 1, 9';
$properties = array("ShortStop","LongStop");
$pyProperties = array("short_stop","long_stop");
$otherProperties = array();
$otherPyProperties = array();
$updateParameterType = 'a <code>TradeBar</code> or <code>QuoteBar</code>';
$constructorArguments = '10, 1, 9';
$updateParameterValue = 'bar';
$hasMovingAverageTypeParameter = False;
$constructorBox = 'chande-kroll-stop';
$isOptionIndicator = false;
include(DOCS_RESOURCES."/indicators/using-indicator.php");
?>