<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'ChandeKrollStop';
$helperName = 'CKS';
$pyHelperName = 'cks';
$helperArguments = 'symbol, 10, 1, 9';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("ShortStop","LongStop");
$pythonProperties = array("short_stop","long_stop");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>