name: Upload Skills to S3

on:
  push:
    paths:
      - '**/SKILL.md'
  workflow_dispatch:  # Run on manual trigger

jobs:
  upload_skills:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Zip skills
        run:  zip -r skills.zip . -i "**/SKILL.md"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET }}
          aws-region: us-west-1
      
      - name: Upload the site to S3
        run: aws s3 cp skills.zip s3://cdn.quantconnect.com/skills --acl bucket-owner-full-control
