name: Check Documentation for Broken Links

on:
  schedule:
    - cron:  "0 10 * * 1-5" # Runs at 10:00 UTC on Mon, Tue, Wed, Thu and Fri. (see https://crontab.guru)
  workflow_dispatch:  # Run on manual trigger

jobs:
  check-urls:
    runs-on: ubuntu-latest

    permissions:
      issues: write

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install dependencies
        run: pip install aiohttp==3.11.14

      - name: Run URL checker
        env:
          GH_TOKEN: ${{ github.token }}
        run: python url_check.py --create-issue
