<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'StochasticRelativeStrengthIndex';
$helperName = 'StochasticRelativeStrengthIndex';
$helperArguments = 'symbol';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("K","D");
$pythonProperties = array("k","d");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>