<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$helperPrefix = '';
$typeName = 'MesaAdaptiveMovingAverage';
$helperName = 'MAMA';
$pyHelperName = 'mama';
$helperArguments = 'symbol, 0.5, 0.05';
$hasReference = false;
$isOptionIndicator = false;
$csharpProperties = array("Fama");
$pythonProperties = array("fama");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>