<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "HeikinAshi";
$indicatorVariable = "heikinashi";
$csharpProperties = array("Open","High","Low","Close","Volume");
$pythonProperties = array("open","high","low","close","volume");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>