<!-- Code generated by indicator_reference_code_generator.py -->
<? 
$typeName = "AverageTrueRange";
$indicatorVariable = "atr";
$csharpProperties = array("TrueRange");
$pythonProperties = array("True_range");
include(DOCS_RESOURCES."/indicators/indicator-history.php");
?>